// Català. Les claus han de coincidir exactament amb UI_ES d'i18n.js (ho comprova el test).
export const CA = {
  ui: {
    wd: ['Diumenge', 'Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres', 'Dissabte'],

    loginKicker: "Registre d'entrenament",
    loginTitle: 'Inicia sessió',
    loginUser: "Nom d'usuari",
    loginPin: 'PIN',
    loginBtn: 'Entrar',
    loginCreateTitle: 'Crear un compte nou',
    loginCreateSub: "Respon un qüestionari d'un minut i l'app et genera rutina i dieta.",
    loginNeedNet: 'El primer cop cal connexió',
    loginBadUser: 'No existeix aquest usuari',
    loginBadPin: 'PIN incorrecte',
    suTitle: 'Crea el teu compte',
    suAccessKicker: 'Accés',
    suName: 'Nom i cognom',
    suUserHint: "Sense espais ni accents. És el que faràs servir per entrar.",
    suPin: 'Tria un PIN (mínim 4 caràcters, números o text)',
    suQuizKicker: 'Qüestionari: amb això es generen la teva rutina i la teva dieta',
    suAge: 'Edat',
    suSex: 'Sexe',
    suSexF: 'Dona',
    suSexM: 'Home',
    suHeight: 'Alçada (cm)',
    suExp: 'Experiència al gimnàs',
    suExp0: "Menys d'1 any",
    suExp1: 'Entre 1 i 3 anys',
    suExp2: 'Més de 3 anys',
    suDays: "Dies d'entreno per setmana",
    suGoal: 'Objectiu',
    suGoalMuscle: 'Guanyar massa muscular',
    suGoalFat: 'Perdre greix',
    suGoalFit: 'Forma física general',
    suCreate: 'Crear compte i començar',
    suNeedName: 'Escriu el teu nom',
    suNeedData: 'Revisa edat, pes i alçada',
    suBadUser: 'Usuari no vàlid: 3-20 lletres o números, sense espais',
    suBadPin: 'El PIN necessita almenys 4 caràcters',
    suTaken: "Aquest nom d'usuari ja existeix",
    suDone: 'Compte creat: aquesta és la teva rutina',

    adminKicker: 'Administració',
    adminTitle: 'Administració',
    adminSub: 'Usuaris, rutines i accessos',
    adminLoading: 'Carregant usuaris…',
    adminView: 'Veure',
    adminEdit: 'Editar rutina',
    adminPin: 'Nou PIN',
    adminDelete: 'Esborrar',
    adminNewPin: 'Nou PIN per a {0} (mínim 4 caràcters):',
    adminPinDone: 'PIN canviat',
    adminConfirmDelete: 'Esborrar el compte de {0}? Els seus registres d’entrenament no es toquen.',
    adminDeleted: 'Compte esborrat',
    adminSaved: 'Rutina desada',
    adminEditSub: 'Editar rutina',
    viewingAs: 'Veient a {0}',
    viewingExit: 'Sortir',
    edRemove: 'Treure',
    edAdd: '+ Afegir exercici…',
    edSave: 'Desar rutina',
    edRepMin: 'Reps mín',
    edRepMax: 'Reps màx',
    edRest: 'Desc. (s)',
    edIncr: 'Incr. (kg)',
    edBad: 'Hi ha valors no vàlids a la rutina',

    tabHome: 'Entreno',
    tabDiet: 'Dieta',
    tabProgress: 'Progrés',
    tabSettings: 'Ajustos',
    back: '‹ Enrere',

    mesoWeek: 'Setmana del mesocicle',
    mesoOf: 'de 5',
    rirTarget: 'RIR objectiu',
    hintDeload: 'Descàrrega: mateix pes, la meitat de les sèries i lluny de la fallada. No te la saltis.',
    hintWeek3: "S'afegeix una sèrie al primer exercici de cada sessió.",
    hintWeek4: 'Setmana pic: la més dura del bloc.',
    hintDefault: 'Apunta cada sèrie. El que no s’apunta, no progressa.',
    todayIs: 'Avui toca {0}',
    todayDone: ' Ja l’has completada, bona feina.',
    restDay: 'Avui toca descansar.',
    nextSession: 'La pròxima sessió és <strong>{0}</strong>, {1}.',
    tomorrow: 'demà',
    inDays: 'd’aquí a {0} dies',
    restIsPlan: 'Descansar forma part del pla: és quan es construeix el múscul.',
    neverLogged: 'Mai registrada',
    doneToday: 'Feta avui',
    yesterday: 'Ahir',
    daysAgo: 'Fa {0} dies',
    today: 'Avui',
    trackingKicker: 'Seguiment',
    bodyCard: 'Pes corporal i cintura',

    offPlanTitle: 'Avui no toca aquesta sessió.',
    offPlanToday: 'Segons el pla, avui et toca <strong>{0}</strong>.',
    offPlanRest: 'Avui és dia de descans al teu pla.',
    offPlanWarn: 'Pots fer-la igualment i es registrarà amb normalitat, però si canvies l’ordre sovint acabaràs entrenant uns grups de més i d’altres de menys.',
    deloadTitle: 'Setmana de descàrrega.',
    deloadBody: 'Sèries reduïdes a la meitat i RIR 4: mateix pes, lluny de la fallada.',
    warmup: 'Escalfament',
    colExercise: 'Exercici',
    colSetsReps: 'Sèries × Reps',
    colRir: 'RIR',
    colRest: 'Descans',
    colStart: 'Càrrega inici',
    colWeight: 'Pes',
    colReps: 'Reps',
    colSecs: 'Seg.',
    perHand: 'kg per mà',
    bodyweight: 'Pes corporal',
    nudgeHint: 'ajusta si el RIR real no quadra',
    lastTime: 'Última vegada · {0}',
    watchVideo: '▶ Veure vídeo real',
    needReps: 'Apunta les repeticions abans de marcar la sèrie',
    legendRir: '<strong>RIR</strong> = repeticions en reserva',
    legendSuperset: '<strong>Supersèrie</strong> = els dos exercicis seguits sense descans',

    restLabel: 'Descans',
    restTarget: 'objectiu {0}',
    restDone: 'Descans complert · a per la següent',
    restAdd: '+30 s',
    restSkip: 'Saltar',

    summary: 'Resum',
    summaryEmpty: 'Registra unes quantes sessions i aquí apareixerà quins exercicis progressen, quins s’han aturat i quant estàs entrenant.',
    statSessions: 'sessions en 4 setmanes',
    statRising: 'exercicis pujant',
    statStalled: 'encallats',
    adhGood: 'Adherència molt bona: 3-4 sessions per setmana sostingudes.',
    adhOk: 'Adherència correcta. Amb una sessió més per setmana el progrés es nota abans.',
    adhBad: '<strong>Estàs entrenant poc</strong> per al pla: són 4 dies per setmana. La constància pesa més que qualsevol ajust de la rutina.',
    bestProgress: 'Millor progressió: <strong>{0}</strong> (+{1} % en les últimes 3 sessions).',
    manyStalled: '<strong>{0} exercicis porten diverses sessions sense pujar.</strong> Si és general, gairebé sempre és menjar o descans, no el programa.',
    someStalled: 'Sense avanç a: {0}. Prova de baixar un 5 % el pes i reconstruir.',
    bodyWeightLine: 'Pes corporal: <strong>{0} kg</strong> ({1} kg en 4 setmanes).',
    waistLine: 'Cintura: <strong>{0} cm</strong> des del primer registre.',
    summaryFoot: 'Tot això surt del teu propi registre. Per revisar-ho amb calma o compartir-ho, a Ajustos pots descarregar l’històric complet en JSON.',
    e1rmKicker: '1RM estimat (Epley)',
    e1rmNote: 'Puja encara que el pes a la barra es quedi quiet. És la mètrica honesta en dèficit calòric.',
    tonnageKicker: 'Tonatge per sessió',
    tonnageNote: 'Pes × repeticions sumat en totes les sèries.',
    history: 'Històric',
    noHistory: 'Encara no has registrat aquest exercici.',
    colDate: 'Data',
    colSets: 'Sèries',
    needTwo: 'Calen com a mínim dos registres per dibuixar l’evolució.',

    bodyTitle: 'Pes i cintura',
    bodyNote: 'Compara <strong>mitjanes setmanals</strong>, mai dies solts. La cintura és el millor indicador: si baixa, vas bé encara que la bàscula s’encalli.',
    fieldWeight: 'Pes corporal (kg)',
    fieldWaist: 'Cintura (cm) — opcional',
    saveToday: 'Desar el d’avui',
    evolution: 'Evolució',
    legendWeight: 'Pes (kg)',
    legendWaist: 'Cintura (cm)',
    records: 'Registres',
    needOneValue: 'Escriu almenys un valor',
    saved: 'Desat',

    dietTitle: 'Dieta',
    kcalDay: 'kcal/dia',
    gProtein: 'g proteïna',
    gCarbs: 'g carbohidrats',
    gFat: 'g greixos',
    proteinLabel: 'Proteïna:',
    sampleDay: 'Dia d’exemple',
    sampleSums: 'Suma <strong>{0} kcal</strong> i <strong>{1} g</strong> de proteïna, per uns <strong>{2} €</strong> al dia.',
    sampleFits: 'Quadra amb el teu objectiu.',
    sampleOver: 'Es queda {0} kcal per sobre: ajusta amb la ració d’arròs, pasta o pa.',
    sampleUnder: 'Es queda {0} kcal per sota: ajusta amb la ració d’arròs, pasta o pa.',
    shoppingBtn: 'Veure la llista de la compra del dia',
    shoppingCopied: 'Llista copiada al porta-retalls',
    shoppingTitle: 'Llista de la compra',
    allRecipes: 'Totes les receptes',
    catBreakfast: 'Esmorzars',
    catLunch: 'Dinars',
    catDinner: 'Sopars',
    catSnack: 'Snacks',
    ingredients: 'Ingredients',
    preparation: 'Preparació',
    halfPortion: '(mitja ració)',
    minShort: 'min',
    dietDisclaimer: 'Les calories són estimacions de taules estàndard i els preus són orientatius: canvien cada temporada. Serveixen per encertar l’objectiu amb un marge del 5-10 %, que és el que importa.',

    settingsTitle: 'Ajustos',
    language: 'Idioma',
    syncKicker: 'Sincronització',
    syncLocal: 'Només local — Supabase sense configurar',
    syncPending: '{0} registre(s) pendents de pujar',
    syncOk: 'Tot sincronitzat',
    lastUpload: 'Última pujada: {0}',
    btnSync: 'Sincronitzar ara',
    btnPull: 'Recuperar del núvol',
    btnExport: 'Descarregar còpia',
    btnImport: 'Restaurar còpia',
    noCloudWarn: 'Sense Supabase configurat les dades viuen només en aquest mòbil. <strong>Safari pot esborrar-les si no obres l’app en ~7 dies.</strong> Descarrega una còpia de tant en tant.',
    syncing: 'Sincronitzant…',
    syncedN: '{0} registre(s) pujats',
    nothingPending: 'Res pendent',
    searchingCloud: 'Buscant al núvol…',
    recovered: 'Recuperades {0} sèries i {1} pesatges',
    nothingToRecover: 'No hi havia res nou per recuperar',
    errorPrefix: 'Error: {0}',
    restored: 'Còpia restaurada',
    badFile: 'Fitxer no vàlid',
    mesoKicker: 'Mesocicle',
    mesoState: 'Setmana <strong>{0} de 5</strong> · va començar el {1}',
    mesoStart: 'Data d’inici',
    mesoReset: 'Començar un mesocicle nou avui',
    mesoResetDone: 'Mesocicle reiniciat a la setmana 1',
    account: 'Compte',
    logout: 'Tancar sessió',
    timerNote: '<strong>Sobre el temporitzador:</strong> el compte és correcte encara que bloquegis el mòbil, però <strong>no sona sol</strong>. iOS no permet alarmes fiables en segon pla sense notificacions push.',
    verChecking: 'comprovant…',
    verUpToDate: 'al dia',
    verAvailable: 'hi ha la v{0} disponible',
    verOffline: 'sense connexió',
    updateNew: 'Hi ha una versió nova <strong>(v{0})</strong>. Tens la v{1}.',
    updateBtn: 'Actualitzar',
    updating: 'Actualitzant…',

    sugStart: 'Primera vegada: càrrega inicial del pla. Ajusta-la fins que el RIR objectiu sigui real.',
    sugDeload: 'Setmana de descàrrega: mateix pes, la meitat de les sèries i lluny de la fallada.',
    sugHoldReps: 'Encara no has arribat a {0} en totes les sèries: repeteix el pes i prova de sumar 1 repetició.',
    sugHoldRir: 'Vas arribar al topall, però sense marge (RIR per sota de {0}): consolida el pes una sessió més.',
    sugLoadBw: 'Topall del rang completat: afegeix 2,5 kg de llast o puja a {0} repeticions.',
    sugLoadPlain: 'Topall del rang completat.',
    sugUp: 'Vas completar {0} reps en totes les sèries amb marge, així que puja a {1} kg.',
    sugUpAssist: 'Vas completar {0} reps en totes les sèries amb marge, així que baixa l’assistència a {1} kg.',
    storageError: 'No s’ha pogut desar. Navegació privada o memòria plena?',
    recoveredFromCloud: 'Recuperats {0} registres del núvol',
  },

  slots: {
    'Desayuno': 'Esmorzar',
    'Media mañana': 'Mig matí',
    'Comida': 'Dinar',
    'Merienda': 'Berenar',
    'Post-entreno': 'Post-entrenament',
    'Media tarde': 'Mitja tarda',
    'Cena': 'Sopar',
    'Antes de dormir': 'Abans de dormir',
  },

  users: {
    jan: { subtitle: "Cinc dies · principiant · guanyar massa muscular" },
    anna: { subtitle: 'Tors–cama · 4 dies · guanyar massa muscular' },
    david: { subtitle: 'Recomposició · 4 dies · prioritat tronc superior' },
  },

  targets: {
    jan: {
      estrategia: 'Superàvit per créixer i guanyar múscul',
      detalle: 'Amb 52 kg per 177 cm estàs per sota del teu pes, i a sobre has posat que estàs en dèficit. Això és exactament el contrari del que necessites: als 15 anys i amb 0-6 mesos de gimnàs, el múscul no apareix per entrenar més, apareix per menjar més. Objectiu: pujar 0,3-0,5 kg al mes. Si la bàscula no es mou en 3 setmanes, no és la rutina — és que estàs menjant poc.',
      proteinaNota: 'Els teus 115 g són el mínim. Amb la proteïna en pols que ja prens hi arribes fàcil, però el que de veritat et falta són les calories: la crema d’arròs i l’arròs, la pasta i el pa són els teus aliats aquí.',
    },
    anna: {
      estrategia: 'Superàvit lleuger per guanyar múscul',
      detalle: 'Amb 52 kg i un 15 % de greix no hi ha res a definir: sense menjar per sobre del manteniment no es construeix teixit nou. L’objectiu és pujar 0,2-0,4 kg al mes, no més — per sobre d’això el que es guanya és greix.',
      proteinaNota: 'El teu mínim són 110 g. Passar-te no és problema; quedar-te curta sí.',
    },
    david: {
      estrategia: 'Dèficit moderat per a recomposició',
      detalle: 'Amb un 27 % de greix i 3-4 anys entrenant, es pot guanyar múscul i perdre greix alhora, però només menjant per sota del manteniment. Objectiu: baixar 0,5-0,7 kg per setmana.',
      proteinaNota: 'Els 190 g són el que protegeix la teva massa magra en dèficit, i a més és el que més et saciarà.',
    },
  },

  days: {
    'j-pecho-a': { name: "Pit, espatlla i tríceps", subtitle: "Empenta · sessió A", warmup: "5 min de bici o el·líptica · mobilitat d’espatlla amb banda (20 rotacions externes) · 15 face pull molt lleugers. Al press banca: barra buida × 15 i després 60 % × 6. Tens 15 anys i portes poc entrenant: la tècnica va primer que els quilos, sempre." },
    'j-espalda-a': { name: "Esquena i bíceps", subtitle: "Estirada · sessió A", warmup: "5 min de rem · 10 penjades passives de la barra de 10 s · 20 rems amb banda. Al rem amb barra: 2 sèries d’aproximació al 50 % i al 70 %." },
    'j-pierna': { name: "Cama", subtitle: "Tren inferior complet", warmup: "5 min de bici · mobilitat de turmell contra la paret (10 per costat) · 90/90 de maluc · 15 ponts de gluti. A la sentadilla: barra buida × 10, 50 % × 5 i 70 % × 3." },
    'j-pecho-b': { name: "Pit, espatlla i tríceps", subtitle: "Empenta · sessió B", warmup: "5 min de rem · mobilitat toràcica · 20 rotacions externes amb banda · 15 face pull lleugers. Al press inclinat: barra buida × 12 i 60 % × 6." },
    'j-espalda-b': { name: "Esquena, braç i abdomen", subtitle: "Estirada · sessió B, amb bessons i avantbraç", warmup: "5 min de bici · 10 penjades passives de la barra · 20 rems amb banda · mobilitat de canell abans del treball d’avantbraç." },
    'a-torso-a': { name: 'Tors A', subtitle: 'Esquena vertical, espatlla i braços', warmup: '5 min de rem o el·líptica suau · mobilitat de columna toràcica (gat-camell, rotacions) · 20 rotacions externes d’espatlla amb banda · dislocacions amb pal. Al jaló: 2 sèries d’aproximació amb el 50 % i el 75 % del pes de treball, 5 reps cadascuna.' },
    'a-pierna-a': { name: 'Cama A', subtitle: 'Dominant de genoll', warmup: '5 min de bicicleta · mobilitat de turmell contra la paret (10 per costat) · 90/90 de maluc · 15 ponts de gluti i 15 passos laterals amb banda. A la sentadilla: barra buida × 10, després 50 % × 5, 70 % × 3 i 85 % × 1.' },
    'a-torso-b': { name: 'Tors B', subtitle: 'Esquena horitzontal, espatlla i braços', warmup: '5 min de rem · mobilitat toràcica de genolls · 20 face pull lleugers · 10 penjades passives de la barra (5-10 s cadascuna). Al rem amb manuella: 1 sèrie d’aproximació al 60 % × 8 per braç.' },
    'a-pierna-b': { name: 'Cama B', subtitle: 'Dominant de maluc i gluti', warmup: '5 min de bicicleta · 90/90 de maluc i estirament del psoes · 20 ponts de gluti amb banda · 15 abduccions dempeus amb banda. Al hip thrust: barra buida × 12 i una altra al 60 % × 8.' },
    'd-empuje': { name: 'Tors A · Empenta', subtitle: 'Pit, espatlla i tríceps', warmup: '5 min de rem o el·líptica · mobilitat de columna toràcica sobre foam roller · 20 rotacions externes d’espatlla amb banda · 15 face pull lleugers. Al press banca: barra buida × 12, després 50 % × 8, 70 % × 5 i 85 % × 2.' },
    'd-tiron': { name: 'Tors B · Estirada', subtitle: 'Esquena, bíceps i trapezi', warmup: '5 min de bicicleta · 10 penjades passives de la barra de 10 s · 20 dislocacions amb pal · 15 rems amb banda. Al rem amb barra: 2 sèries d’aproximació al 50 % i al 75 %, 6 reps cadascuna.' },
    'd-pierna': { name: 'Cama + core', subtitle: 'Manteniment eficient', warmup: '5 min de bicicleta · mobilitat de turmell contra la paret (10 per costat) · 90/90 de maluc i estirament de psoes · 15 ponts de gluti. A la sentadilla: barra buida × 10, 50 % × 5, 70 % × 3, 85 % × 1.' },
    'd-completo': { name: 'Tors C · Complet', subtitle: 'Pit superior, esquena i espatlles', warmup: '5 min de rem · mobilitat toràcica sobre foam roller · 20 rotacions externes amb banda · 15 face pull lleugers. Al press inclinat: barra buida × 12, 55 % × 8 i 75 % × 4.' },
  },

  ex: {
    'j-dead-bug': { name: 'Dead bug ("insecte mort")', cue: 'De panxa enlaire, baixes braç i cama contraris sense que la lumbar es desenganxi de terra. 10 per costat, lent.' },
    'j-press-banca': { name: "Press banca amb barra", cue: "Escàpules retretes, colzes a 45-60°. Baixa en 2 s i toca el pit sense rebotar. Derivat del teu 90 × 2: comença a 75 kg." },
    'j-press-inclinado-mancuernas': { name: "Press inclinat amb manuelles (30°)", cue: "Pit superior: la zona que més defineix l’aspecte del tors vestit." },
    'j-press-hombro-mancuernas': { name: "Press d’espatlla assegut amb manuelles", cue: "Respatller a 85°. Reps més altes que dilluns per acumular volum sense repetir fatiga." },
    'j-aperturas-polea': { name: "Obertures a la politja (creuament de pit)", cue: "Supersèrie amb el següent. Politges a l’alçada de l’espatlla, junta les mans al davant i estreny 1 s." },
    'j-triceps-cuerda': { name: "Extensió de tríceps a la politja amb corda", cue: "Supersèrie amb el següent. Colzes enganxats al costat, obre la corda al final." },
    'j-press-frances': { name: "Press francès amb barra Z", cue: "Supersèrie amb l’anterior. Treballa la porció llarga del tríceps." },
    'j-plancha': { name: "Planxa frontal", cue: "Gluti estret i pelvis en retroversió. Millor 30 s ben fets que 60 s amb el maluc caigut." },
    'j-jalon-neutro': { name: "Jaló al pit, presa neutra", cue: "Pit alt, colzes cap a les costelles. Pausa d’1 s a baix." },
    'j-face-pull': { name: "Face pull a la politja alta", cue: "Colzes alts, rotació externa al final. El millor antídot contra l’espatlla avançada." },
    'j-curl-barra-z': { name: "Curl de bíceps amb barra Z", cue: "Supersèrie amb el següent. Colzes quiets al costat del tronc, sense balanceig de maluc." },
    'j-curl-martillo': { name: "Curl martell amb manuelles", cue: "Supersèrie amb l’anterior. Palmells encarats: treballa el braquial." },
    'j-rdl': { name: "Pes mort romanès amb barra", cue: "Maluc enrere, barra fregant la cuixa. Atura’t quan perdis la curvatura lumbar." },
    'j-prensa': { name: "Premsa 45°", cue: "Peus a mitja alçada. No bloquegis els genolls a dalt; baixada controlada de 2 s." },
    'j-femoral-tumbado': { name: "Curl femoral estirat", cue: "Maluc enganxat al banc, excèntrica lenta de 3 s. Compensa les hores d’isqui escurçat a la cadira." },
    'j-extension-cuadriceps': { name: "Extensió de quàdriceps", cue: "Pausa d’1 s a dalt. Última sèrie amb 2-3 reps parcials." },
    'j-gemelo-pie': { name: "Elevació de talons dempeus", cue: "Recorregut complet: estira 2 s a baix, estreny 1 s a dalt." },
    'j-rueda-abdominal': { name: "Roda abdominal o planxa frontal", cue: "Pelvis en retroversió, sense deixar caure el maluc. Això no crema la panxa: això ho fa el dèficit." },
    'j-press-inclinado-barra': { name: "Press inclinat amb barra (30°)", cue: "L’exercici amb millor relació esforç/resultat visible en el teu cas. Aquí és el principal." },
    'j-press-militar': { name: "Press militar amb barra, dempeus", cue: "Gluti i abdomen estrets per no arquejar la lumbar. Cap enrere en passar la barra." },
    'j-fondos': { name: "Fons a paral·leles", cue: "Tronc una mica inclinat endavant per carregar pit. Si no arribes a 8, fes servir la màquina assistida." },
    'j-encogimientos': { name: "Encongiments d’espatlla amb manuelles", cue: "Puja recte, sense rotar. Pausa d’1 s a dalt." },
    'j-remo-mancuerna': { name: "Rem amb manuella a una mà", cue: "Genoll i mà al banc. Recorregut llarg i estirament complet a baix. 10-12 per braç." },
    'j-jalon-prono': { name: "Jaló al pit, presa prona ampla", cue: "Pit alt, estira amb els colzes cap a les costelles. Sense balanceig." },
    'j-curl-inclinado': { name: "Curl bíceps al banc inclinat", cue: "Braç per darrere del tronc, estirament complet a baix." },
    'j-gemelo-sentado': { name: "Elevació de talons asseguda", cue: "Treballa el soli. Reps altes, tempo lent." },
    'j-elevacion-piernas': { name: "Elevació de cames estirada a terra", cue: "Mans sota els glutis, lumbar enganxada a terra. Baixa les cames només fins on puguis mantenir-la enganxada." },
    'j-plancha-lateral': { name: "Planxa lateral", cue: "Suport a l’avantbraç, maluc ben alt i alineat. 20-30 s per costat, alternant." },
    'j-laterales': { name: "Elevacions laterals amb manuelles", cue: "Puja a l’horitzontal i baixa en 3 s. Pes lleuger: si t’has de balancejar, en sobra." },
    'j-dominada-asistida': { name: "Dominada assistida", cue: "Amb màquina o amb goma. A més assistència, més fàcil. L’objectiu del bloc és baixar l’assistència, no pujar repeticions sense més." },
    'j-remo-barra': { name: "Rem amb barra a 45°", cue: "Tronc ferm i estira cap al melic. Si la lumbar s’arrodoneix, baixa pes: amb 15 anys això no es negocia." },
    'j-sentadilla': { name: "Sentadilla darrere amb barra", cue: "Setmanes 1 i 2 amb barra buida fins que el patró surti sol. Profunditat fins a paral·lel, genolls seguint la punta del peu." },
    'j-laterales-polea': { name: "Elevacions laterals a la politja", cue: "A la politja la tensió també és a baix, al revés que amb manuella dilluns. Per això hi són els dos dies." },
    'j-deltoide-polea': { name: "Deltoide posterior a la politja", cue: "Braç creuat per davant del cos, obres cap enfora i enrere amb el colze gairebé recte." },
    'j-triceps-barra': { name: "Extensió de tríceps a la politja, barra recta", cue: "Mateix moviment que dilluns però amb barra en lloc de corda: canvia la presa i l’estímul." },
    'j-rdl-mancuernas': { name: "Pes mort romanès amb manuelles", cue: "Complementa la cama de dimecres sense carregar la lumbar com la barra. Maluc enrere, esquena recta." },
    'j-granjero': { name: "Caminada del granger amb manuelles", cue: "El teu treball d’avantbraç. Espatlles enrere, abdomen estret i passes curtes. La presa és el que limita el rem i les dominades, així que això et fa més fort en tota la resta." },
    // --- Anna, Tors A
    'a-jalon-prono': { name: 'Jaló al pit, presa prona ampla', cue: 'Pit alt, estira amb els colzes cap a les costelles. Sense balanceig.' },
    'a-press-banca-mancuernas': { name: 'Press banca pla amb manuelles', cue: 'Manteniment de pectoral. Recorregut complet, sense buscar rècords.' },
    'a-press-militar-mancuernas': { name: 'Press militar asseguda amb manuelles', cue: 'Respatller a 80-85°, costelles avall per no arquejar la lumbar.' },
    'a-laterales': { name: "Elevacions laterals amb manuelles", cue: "Puja fins a l’horitzontal, baixa en 2-3 s. Zero impuls de maluc. Amb manuella el més dur és a dalt; a la politja de dijous és a baix. Per això hi són les dues: l’espatlla necessita dos estímuls per setmana i així no es repeteix la sensació." },
    'a-face-pull': { name: "Face pull a la politja alta", cue: "Supersèrie amb l’anterior. Colzes alts i rotació externa al final: això és espatlla posterior més rotadors, no l’obertura pura de dijous. És el que compensa les hores d’espatlla avançada." },
    'a-curl-inclinado': { name: 'Curl bíceps al banc inclinat', cue: 'Braç per darrere del tronc, estirament complet a baix.' },
    'a-remo-mancuerna': { name: "Rem amb manuella a una mà", cue: "Una mà i un genoll al banc. 10-12 per braç. Fes-ho amb manuella encara que tinguis la màquina al costat: el rem assegut ja el tens dijous, i a una mà treballes cada costat per separat i el core aguantant la rotació." },
    'a-press-frances': { name: "Press francès amb manuelles", cue: "Supersèrie amb el curl. Estirada al banc, baixes les manuelles cap al front amb els colzes quiets. És un patró diferent del de la politja de dijous: aquí el tríceps treballa estirat, que és on més creix." },
    'a-plancha': { name: 'Planxa frontal', cue: 'Gluti estret, pelvis en retroversió. Qualitat per sobre de durada.' },
    // --- Anna, Cama A
    'a-sentadilla': { name: 'Sentadilla darrere amb barra', cue: 'Setmana 1: barra buida (20 kg) fins que el patró surti sol. Profunditat fins a paral·lel o una mica més.' },
    'a-rdl': { name: 'Pes mort romanès amb barra', cue: 'Maluc enrere, barra fregant la cuixa. Atura’t quan perdis la curvatura lumbar.' },
    'a-prensa': { name: 'Premsa 45°, peus a mitja alçada', cue: 'No bloquegis els genolls a dalt. Baixada controlada de 2 s.' },
    'a-femoral-tumbada': { name: 'Curl femoral estirada', cue: 'Maluc enganxat al banc; excèntrica lenta de 3 s.' },
    'a-extension-cuadriceps': { name: 'Extensió de quàdriceps', cue: 'Pausa d’1 s a dalt. Última sèrie amb 2-3 reps parcials.' },
    'a-gemelo-pie': { name: 'Elevació de talons dempeus', cue: 'Recorregut complet: estira 2 s a baix, estreny 1 s a dalt.' },
    'a-plancha-lateral': { name: 'Planxa lateral', cue: 'Suport a l’avantbraç, maluc ben alt i alineat. Alternant costats.' },
    // --- Anna, Tors B
    'a-dominada-asistida': { name: 'Dominada assistida a màquina', cue: 'A més quilos d’assistència, més fàcil. Objectiu del bloc: baixar l’assistència.' },
    'a-press-inclinado-mancuernas': { name: 'Press inclinat amb manuelles (30°)', cue: 'Manteniment de pectoral. 2 sèries efectives ja fan si vas justa de temps.' },
    'a-remo-maquina': { name: "Rem assegut a màquina", cue: "Pit recolzat al respatller si la màquina en té. Estira amb els colzes, pausa d’1 s amb les escàpules juntes i deixa anar a poc a poc." },
    'a-lateral-polea': { name: "Elevació lateral unilateral a la politja", cue: "Un braç cada cop, politja baixa creuada per darrere del cos. Tensió constant també a la part baixa del recorregut, que és el que no et dona la manuella." },
    'a-deltoide-polea': { name: "Deltoide posterior a la politja unilateral", cue: "Politja a l’alçada de l’espatlla, agafes la nansa amb el braç creuat per davant del cos i obres cap enfora i enrere. Colze gairebé recte. Substitueix el pec-deck invertit, que al teu gimnàs no hi ha." },
    'a-pullover': { name: 'Pull-over a la politja alta', cue: 'Braços gairebé rectes, aïlla el dorsal sense implicar bíceps.' },
    'a-curl-martillo': { name: 'Curl martell amb manuelles', cue: 'Palmells encarats. Treballa el braquial: engrossa el braç.' },
    'a-triceps-barra': { name: 'Extensió de tríceps a la politja alta, barra recta', cue: 'Supersèrie amb el curl. Politja de dalt, colzes enganxats al costat i quiets. Presa de barra en lloc de corda per canviar l’estímul respecte a dilluns.' },
    'a-crunch-piernas': { name: 'Elevació de cames estirada a terra', cue: 'Mans sota els glutis, lumbar enganxada a terra. Baixa les cames només fins on puguis mantenir-la enganxada.' },
    // --- Anna, Cama B
    'a-hip-thrust': { name: 'Hip thrust a màquina (càrrega amb discos)', cue: 'Esquena recolzada al respatller, coixinet sobre el maluc. Barbeta al pit i pausa d’1 s a dalt sense hiperextendre la lumbar. Els quilos són els discos que hi poses: cada disc de 2,5 per costat són +5 kg.' },
    'a-bulgara': { name: 'Sentadilla búlgara amb manuelles', cue: 'Comença sense pes fins a dominar l’equilibri. 8-10 per cama.' },
    'a-femoral-sentada': { name: 'Curl femoral estirada', cue: 'Mateix exercici que dimarts però amb més repeticions. Maluc enganxat al banc i excèntrica lenta de 3 s.' },
    'a-prensa-alta': { name: 'Premsa amb peus alts i amples', cue: 'Emfatitza gluti i isquis. Recorregut profund sense desenganxar la lumbar.' },
    'a-abduccion': { name: 'Abducció de maluc a màquina', cue: 'Tronc lleugerament avançat. Pausa d’1 s en obertura màxima.' },
    'a-gemelo-sentada': { name: 'Elevació de talons asseguda', cue: 'Treballa el soli. Reps altes, tempo lent.' },
    'a-granjero': { name: 'Caminada del granger amb manuelles', cue: 'Espatlles enrere, abdomen estret i passes curtes. No deixis que el pes t’inclini cap a un costat: això és justament el que estàs entrenant. Vau començar amb 10 kg per mà; puja quan aguantis els 45 s sencers sense perdre la postura.' },
    'a-dead-bug': { name: 'Dead bug ("insecte mort")', cue: 'Baixes braç i cama contraris sense que la lumbar es desenganxi de terra. 10 per costat.' },

    // --- David, Empenta
    'd-press-banca': { name: 'Press banca amb barra', cue: 'Escàpules retretes, colzes a 45-60°. Baixa en 2 s i toca el pit sense rebotar. Derivat del teu 90 × 2: comença a 75 kg.' },
    'd-press-militar': { name: 'Press militar amb barra, dempeus', cue: 'Gluti i abdomen estrets per no arquejar la lumbar. Cap enrere en passar la barra.' },
    'd-press-inclinado-mancuernas': { name: 'Press inclinat amb manuelles (30°)', cue: 'Pit superior: la zona que més defineix l’aspecte del tors vestit.' },
    'd-fondos': { name: 'Fons a paral·leles', cue: 'Tronc una mica inclinat endavant per carregar pit. Si no arribes a 8, fes servir la màquina assistida.' },
    'd-laterales-polea': { name: 'Elevacions laterals a la politja', cue: 'Puja a l’horitzontal, baixa en 3 s. Un braç cada cop o els dos a politja baixa creuada.' },
    'd-triceps-cuerda': { name: 'Extensió de tríceps a la politja amb corda', cue: 'Supersèrie amb el següent. Colzes enganxats al costat, obre la corda al final.' },
    'd-press-frances': { name: 'Press francès amb barra Z', cue: 'Supersèrie amb l’anterior. Treballa la porció llarga del tríceps.' },
    'd-plancha': { name: 'Planxa frontal', cue: 'Gluti estret i pelvis en retroversió. Millor 30 s ben fets que 60 s amb el maluc caigut.' },
    // --- David, Estirada
    'd-dominadas': { name: 'Dominades (presa prona)', cue: 'Sense assistència: ja en fas 4 × 5. Excèntrica de 3 s. Quan arribis a 4 × 8 netes, afegeix 2,5 kg de llast.' },
    'd-remo-barra': { name: 'Rem amb barra a 45°', cue: 'Tronc ferm, estira cap al melic. Si la lumbar s’arrodoneix, baixa pes: això no es negocia.' },
    'd-jalon': { name: 'Jaló al pit, presa neutra', cue: 'Pit alt, colzes cap a les costelles. Pausa d’1 s a baix.' },
    'd-remo-supino': { name: 'Rem assegut a la politja, presa supina', cue: 'La presa supina carrega més el dorsal baix. Pausa d’1 s, sense tirar el tronc enrere.' },
    'd-face-pull': { name: 'Face pull a la politja alta', cue: 'Colzes alts, rotació externa al final. El millor antídot contra l’espatlla avançada.' },
    'd-encogimientos': { name: 'Encongiments d’espatlla amb manuelles', cue: 'Puja recte, sense rotar. Pausa d’1 s a dalt.' },
    'd-curl-barra-z': { name: 'Curl de bíceps amb barra Z', cue: 'Supersèrie amb el següent. Colzes quiets al costat del tronc, sense balanceig de maluc.' },
    'd-curl-martillo': { name: 'Curl martell amb manuelles', cue: 'Supersèrie amb l’anterior. Palmells encarats: treballa el braquial.' },
    'd-plancha-lateral': { name: 'Planxa lateral', cue: 'Suport a l’avantbraç, maluc ben alt i alineat. 20-30 s per costat, alternant.' },
    // --- David, Cama
    'd-sentadilla': { name: 'Sentadilla darrere amb barra', cue: 'Sense dades prèvies de cama: la setmana 1 és de calibratge pur. Puja sense por si el RIR real et surt a 4.' },
    'd-rdl': { name: 'Pes mort romanès amb barra', cue: 'Maluc enrere, barra fregant la cuixa. Atura’t quan perdis la curvatura lumbar.' },
    'd-prensa': { name: 'Premsa 45°', cue: 'Peus a mitja alçada. No bloquegis els genolls a dalt; baixada controlada de 2 s.' },
    'd-femoral-sentado': { name: 'Curl femoral estirat', cue: 'Maluc enganxat al banc, excèntrica lenta de 3 s. Compensa les hores d’isqui escurçat a la cadira.' },
    'd-gemelo-pie': { name: 'Elevació de talons dempeus', cue: 'Recorregut complet: estira 2 s a baix, estreny 1 s a dalt.' },
    'd-rueda-abdominal': { name: 'Roda abdominal o planxa frontal', cue: 'Pelvis en retroversió, sense deixar caure el maluc. Això no crema la panxa: això ho fa el dèficit.' },
    'd-granjero': { name: 'Caminada del granger amb manuelles', cue: 'Espatlles enrere, abdomen estret i passes curtes. No deixis que el pes t’inclini cap a un costat. Vau provar amb 10 kg per mà: per al teu pes corporal et quedaràs curt de seguida, puja quan aguantis els 45 s sense despentinar-te.' },
    // --- David, Complet
    'd-press-inclinado-barra': { name: 'Press inclinat amb barra (30°)', cue: 'L’exercici amb millor relació esforç/resultat visible en el teu cas. Aquí és el principal.' },
    'd-remo-mancuerna': { name: 'Rem amb manuella a una mà', cue: 'Genoll i mà al banc. Recorregut llarg i estirament complet a baix. 10-12 per braç.' },
    'd-press-hombro-mancuernas': { name: 'Press d’espatlla assegut amb manuelles', cue: 'Respatller a 85°. Reps més altes que dilluns per acumular volum sense repetir fatiga.' },
    'd-pullover': { name: 'Pull-over a la politja alta', cue: 'Braços gairebé rectes: aïlla el dorsal sense implicar bíceps. És el que eixampla l’esquena vista de front.' },
    'd-aperturas-polea': { name: 'Obertures a la politja (creuament de pit)', cue: 'Supersèrie amb el següent. Politges a l’alçada de l’espatlla, junta les mans al davant i estreny 1 s.' },
    'd-laterales-mancuernas': { name: 'Elevacions laterals amb manuelles', cue: 'Supersèrie amb l’anterior. Última sèrie: 3 repeticions parcials en acabar.' },
    'd-pajaros': { name: 'Ocells amb manuelles (tronc inclinat)', cue: 'Assegut a la vora del banc, pit cap a les cuixes. Obre els braços enrere amb els colzes gairebé rectes. Pes lleuger: aquí mana la sensació, no els quilos.' },
    'd-dead-bug': { name: 'Dead bug ("insecte mort")', cue: 'De panxa enlaire, baixes braç i cama contraris sense que la lumbar es desenganxi de terra. 10 per costat, lent.' },
  },

  meals: {
    'avena-yogur': { name: 'Iogurt proteic amb civada, plàtan i cacauet', ingredients: ['1 iogurt proteic natural (200 g)', '60 g de flocs de civada', '1 plàtan', '15 g de crema de cacauet', 'Canyella'], steps: ['Posa la civada en un bol i cobreix-la amb el iogurt.', 'Talla el plàtan a sobre i afegeix la crema de cacauet.', 'Si ho deixes fet la nit abans, la civada queda tova i es menja millor.'] },
    'tortilla-pavo': { name: 'Truita de 3 ous amb gall dindi i pa', ingredients: ['3 ous', '60 g de gall dindi a llesques', '2 llesques de pa integral', 'Sal i oli d’oliva'], steps: ['Bat els ous amb el gall dindi trossejat i un pessic de sal.', 'Qualla-ho a la paella amb un raig d’oli, 3-4 min.', 'Torra el pa i serveix.'] },
    'batido-avena': { name: 'Batut de civada, llet, plàtan i cacau', ingredients: ['350 ml de llet sencera', '50 g de flocs de civada', '1 plàtan', '1 cullerada de cacau pur desgreixat', 'Opcional: 1 mesura de proteïna'], steps: ['Tot a la batedora, 30 segons.', 'És l’opció per als matins amb pressa: es beu de camí.'] },
    'tostadas-huevo': { name: 'Torrades amb ou i alvocat', ingredients: ['2 llesques de pa integral', '2 ous', '1/2 alvocat', 'Sal, pebre i oli d’oliva'], steps: ['Torra el pa i aixafa-hi l’alvocat.', 'Fes els ous a la planxa i posa’ls a sobre.', 'Sal, pebre i llest.'] },
    'arroz-pollo': { name: 'Arròs amb pollastre i verdures saltades', ingredients: ['100 g d’arròs basmati (en cru)', '180 g de pit de pollastre a filets', '200 g de verdura per a wok congelada', 'Salsa de soja', 'Oli d’oliva'], steps: ['Posa l’arròs a bullir, 10-12 min.', 'Mentrestant, salta el pollastre trossejat a la paella amb una mica d’oli.', 'Afegeix la verdura congelada directa del paquet i salta 5 min més.', 'Barreja-ho tot amb l’arròs i un raig de soja.'], tip: 'Cuina l’arròs i el pollastre per a 3 dies de cop: la diferència entre complir la dieta i no complir-la sol ser tenir el menjar ja fet.' },
    'pasta-atun': { name: 'Pasta amb tonyina i tomàquet', ingredients: ['100 g de pasta (en cru)', '2 llaunes de tonyina al natural', '200 g de tomàquet fregit o triturat', 'All en pols i orenga'], steps: ['Bull la pasta.', 'Escalfa el tomàquet amb la tonyina escorreguda, all i orenga, 5 min.', 'Barreja-ho.'] },
    'lentejas-huevo': { name: 'Llenties de pot amb arròs i ou', ingredients: ['1 pot de llenties cuites (400 g)', '60 g d’arròs (en cru)', '2 ous', 'Pebre vermell i oli d’oliva'], steps: ['Esbandeix les llenties i escalfa-les amb una mica de pebre vermell.', 'Bull l’arròs i els ous (10 min els ous).', 'Tot junt al plat.'], tip: 'Del més barat que menjaràs amb aquesta quantitat de proteïna.' },
    'pollo-boniato': { name: 'Pollastre al forn amb moniato i amanida', ingredients: ['200 g de pit de pollastre', '250 g de moniato', 'Bossa d’amanida', 'Espècies, sal i oli d’oliva'], steps: ['Talla el moniato a grills, oli i sal, al forn 200 °C, 25 min.', 'Als 10 min posa-hi el pollastre amb espècies a la mateixa safata.', 'Serveix amb l’amanida amanida.'], tip: 'Fes-ne el triple: és la mateixa mitja hora de forn i et resol tres àpats.' },
    'wok-ternera': { name: 'Wok de vedella amb noodles i verdura', ingredients: ['180 g de vedella a tires', '2 nius de noodles', '200 g de verdura per a wok congelada', 'Salsa de soja i all'], steps: ['Hidrata els noodles segons el paquet (3 min).', 'Salta la vedella 3 min a foc fort.', 'Afegeix la verdura, 4 min més, i barreja-ho amb els noodles i la soja.'] },
    'salmon-patata': { name: 'Salmó al forn amb patata i bròquil', ingredients: ['180 g de salmó', '250 g de patata', '200 g de bròquil (val congelat)', 'Llimona, sal i oli d’oliva'], steps: ['Patata a rodanxes al forn 200 °C, 20 min.', 'Afegeix el salmó i el bròquil, 12 min més.', 'Llimona per sobre en treure-ho.'], tip: 'El menjar més car de la llista, però el de millors greixos. Un cop per setmana.' },
    'revuelto-gambas': { name: 'Remenat d’ous amb gambes i espinacs', ingredients: ['3 ous', '100 g de gambes pelades congelades', '150 g d’espinacs frescos', 'All i oli d’oliva'], steps: ['Salta l’all i les gambes 3 min.', 'Afegeix els espinacs fins que baixin.', 'Aboca-hi els ous batuts i remena fins que qualli.'] },
    'merluza-verduras': { name: 'Lluç a la planxa amb verdures i pa', ingredients: ['200 g de lloms de lluç congelat', '250 g de verdura variada congelada', '1 llesca de pa', 'Llimona, all i oli'], steps: ['Verdura al microones, 6 min.', 'Lluç a la planxa 4 min per costat amb all.', 'Llimona i a menjar.'] },
    'ensalada-completa': { name: 'Amanida completa de tonyina, ou i cigrons', ingredients: ['Bossa d’amanida', '1 pot petit de cigrons cuits', '2 llaunes de tonyina', '2 ous durs', 'Blat de moro, oli i vinagre'], steps: ['Esbandeix els cigrons.', 'Barreja-ho tot en un bol gran.', 'Amaneix amb oli, vinagre i sal.'], tip: 'Zero cuina i surt en 8 minuts. El sopar dels dies que no et ve de gust res.' },
    'pollo-hummus': { name: 'Pit a la planxa amb hummus i pa de pita', ingredients: ['200 g de pit de pollastre', '80 g d’hummus', '1 pa de pita integral', 'Tomàquet i enciam'], steps: ['Pollastre a la planxa amb sal i espècies, 5 min per costat.', 'Escalfa la pita 1 min.', 'Munta-ho tot amb l’hummus i la verdura.'] },
    'tortilla-patata': { name: 'Truita de patata ràpida al microones', ingredients: ['300 g de patata', '3 ous', 'Ceba (opcional)', 'Sal i oli d’oliva'], steps: ['Patata a daus amb una mica d’oli, al microones 8 min tapada.', 'Barreja-ho amb els ous batuts i sal.', 'Al microones 3-4 min més, o qualla-ho a la paella.'] },
    'yogur-almendras': { name: 'Iogurt proteic amb ametlles', ingredients: ['1 iogurt proteic (200 g)', '20 g d’ametlles'], steps: ['Res per cuinar.'] },
    'tostada-cacahuete': { name: 'Torrada amb crema de cacauet i plàtan', ingredients: ['2 llesques de pa integral', '20 g de crema de cacauet', '1 plàtan'], steps: ['Torra, unta, talla el plàtan a sobre.'] },
    'batido-proteina': { name: 'Batut de proteïna amb llet', ingredients: ['1 mesura de proteïna en pols (30 g)', '300 ml de llet'], steps: ['Agitar.'], tip: 'La manera més ràpida i barata de sumar 30 g de proteïna quan el dia va just.' },
    'requeson-fruta': { name: 'Mató amb fruita i mel', ingredients: ['200 g de mató o formatge batut 0 %', '1 peça de fruita', '1 culleradeta de mel'], steps: ['Barrejar.'] },
    'atun-tostadas': { name: 'Torrades amb tonyina', ingredients: ['2 llaunes de tonyina al natural', '2 llesques de pa integral', 'Tomàquet i oli'], steps: ['Torra el pa, frega-hi tomàquet i posa-hi la tonyina escorreguda.'] },
  },
};
