// English. Keys must match UI_ES in i18n.js exactly (the test checks this).
export const EN = {
  ui: {
    wd: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],

    loginKicker: 'Training log',
    loginTitle: 'Sign in',
    loginUser: 'Username',
    loginPin: 'PIN',
    loginBtn: 'Sign in',
    loginShowPin: 'Show PIN',
    loginCreateTitle: 'Create a new account',
    loginCreateSub: 'Answer a one-minute questionnaire and the app generates your routine and diet.',
    loginNeedNet: 'You need a connection the first time',
    loginBadUser: 'That user does not exist',
    loginBadPin: 'Wrong PIN',
    suTitle: 'Create your account',
    suAccessKicker: 'Access',
    suName: 'First and last name',
    suUserHint: 'No spaces or accents. This is what you will sign in with.',
    suPin: 'Choose a PIN (at least 4 characters, numbers or text)',
    suQuizKicker: 'Questionnaire: this generates your routine and your diet',
    suAge: 'Age',
    suSex: 'Sex',
    suSexF: 'Female',
    suSexM: 'Male',
    suHeight: 'Height (cm)',
    suExp: 'Gym experience',
    suExp0: 'Less than 1 year',
    suExp1: '1 to 3 years',
    suExp2: 'More than 3 years',
    suDays: 'Training days per week',
    suGoal: 'Goal',
    suGoalMuscle: 'Build muscle',
    suGoalFat: 'Lose fat',
    suGoalFit: 'General fitness',
    suGoalRace: 'Train for an endurance event',
    suAboutYou: 'About you',
    suTraining: 'Your training',
    suMinutes: 'How long a session lasts',
    suMin30: '30 min',
    suMin45: '45 min',
    suMin60: '1 hour',
    suMin75: 'More than 1 hour',
    suSport: 'Other sport besides the gym',
    suSportNone: 'None',
    suSportRun: 'Running or trail',
    suSportBike: 'Cycling',
    suSportSwim: 'Swimming',
    suSportTeam: 'Team sport',
    suSportOther: 'Other',
    suSportDays: 'Days of that sport per week',
    suNiggle: 'Any niggle',
    suNiggleNone: 'None',
    suNiggleShoulder: 'Shoulder',
    suNiggleKnee: 'Knee',
    suNiggleBack: 'Lower back',
    suNiggleNote: 'Pick one and the exercises that load it most are dropped. A niggle that does not clear up in two weeks is for a physio, not an app.',
    suCreate: 'Create account and start',
    suNeedName: 'Enter your name',
    suNeedData: 'Check age, weight and height',
    suBadUser: 'Invalid username: 3-20 letters or numbers, no spaces',
    suBadPin: 'The PIN needs at least 4 characters',
    suTaken: 'That username already exists',
    suDone: 'Account created: this is your routine',

    adminKicker: 'Administration',
    adminTitle: 'Administration',
    adminSub: 'Users, routines and access',
    adminLoading: 'Loading users…',
    adminView: 'View',
    adminEdit: 'Edit routine',
    adminPin: 'New PIN',
    adminDelete: 'Delete',
    adminNewPin: 'New PIN for {0} (at least 4 characters):',
    adminPinDone: 'PIN changed',
    adminConfirmDelete: 'Delete {0}’s account? Their training logs are not touched.',
    adminDeleted: 'Account deleted',
    adminSaved: 'Routine saved',
    adminEditSub: 'Edit routine',
    viewingAs: 'Viewing {0}',
    viewingExit: 'Exit',
    edRemove: 'Remove',
    edAdd: '+ Add exercise…',
    edSave: 'Save routine',
    edRepMin: 'Min reps',
    edRepMax: 'Max reps',
    edRest: 'Rest (s)',
    edIncr: 'Incr. (kg)',
    edBad: 'The routine has invalid values',

    tabHome: 'Train',
    tabDiet: 'Diet',
    tabProgress: 'Progress',
    tabSettings: 'Settings',
    back: '‹ Back',

    mesoWeek: 'Mesocycle week',
    mesoOf: 'of 5',
    rirTarget: 'Target RIR',
    hintWeek1: 'Easy week of the block: high RIR. That is the recovery, not a wasted day.',
    hintWeek3: 'One extra set is added to the first exercise of each session.',
    hintWeek4: 'Peak week: the hardest of the block.',
    hintDefault: 'Log every set. What you do not log does not progress.',
    todayIs: 'Today is {0}',
    todayDone: ' Already done, good work.',
    restDay: 'Today is a rest day.',
    nextSession: 'Next session is <strong>{0}</strong>, {1}.',
    tomorrow: 'tomorrow',
    inDays: 'in {0} days',
    restIsPlan: 'Resting is part of the plan: that is when muscle is built.',
    neverLogged: 'Never logged',
    doneToday: 'Done today',
    yesterday: 'Yesterday',
    daysAgo: '{0} days ago',
    today: 'Today',
    weekKicker: 'This week',
    weekLeft: '{0} to go',
    weekAllDone: 'week complete',
    trackingKicker: 'Tracking',
    bodyCard: 'Body weight and waist',

    offPlanTitle: 'This is not today’s session.',
    offPlanToday: 'According to the plan, today is <strong>{0}</strong>.',
    offPlanRest: 'Today is a rest day in your plan.',
    offPlanWarn: 'You can do it anyway and it will be logged normally, but if you keep changing the order you will end up training some muscle groups too much and others too little.',
    warmup: 'Warm-up',
    colExercise: 'Exercise',
    colSetsReps: 'Sets × Reps',
    colRir: 'RIR',
    colRest: 'Rest',
    colStart: 'Start load',
    colWeight: 'Weight',
    colReps: 'Reps',
    colSecs: 'Secs',
    perHand: 'kg per hand',
    bodyweight: 'Bodyweight',
    nudgeHint: 'adjust if the real RIR does not match',
    lastTime: 'Last time · {0}',
    watchVideo: '▶ Watch real video',
    needReps: 'Enter the reps before ticking the set',
    legendRir: '<strong>RIR</strong> = reps in reserve',
    legendSuperset: '<strong>Superset</strong> = both exercises back to back with no rest',

    restLabel: 'Rest',
    restTarget: 'target {0}',
    restDone: 'Rest complete · go for the next one',
    restAdd: '+30 s',
    restSkip: 'Skip',

    summary: 'Summary',
    summaryEmpty: 'Log a few sessions and this will show which exercises are progressing, which have stalled and how much you are actually training.',
    statSessions: 'sessions in 4 weeks',
    statRising: 'exercises rising',
    statStalled: 'stalled',
    adhGood: 'Very good adherence: 3-4 sessions per week, sustained.',
    adhOk: 'Adherence is fine. One more session per week and progress shows sooner.',
    adhBad: '<strong>You are training too little</strong> for this plan: it is 4 days a week. Consistency matters more than any tweak to the routine.',
    bestProgress: 'Best progression: <strong>{0}</strong> (+{1} % over the last 3 sessions).',
    manyStalled: '<strong>{0} exercises have gone several sessions without going up.</strong> If it is across the board, it is almost always food or sleep, not the programme.',
    someStalled: 'No progress on: {0}. Try dropping the weight 5 % and building back up.',
    bodyWeightLine: 'Body weight: <strong>{0} kg</strong> ({1} kg over 4 weeks).',
    waistLine: 'Waist: <strong>{0} cm</strong> since the first entry.',
    summaryFoot: 'All of this comes from your own log. To go through it properly or share it, you can download the full history as JSON in Settings.',
    e1rmKicker: 'Estimated 1RM (Epley)',
    e1rmNote: 'It goes up even when the bar weight stays put. It is the honest metric in a calorie deficit.',
    tonnageKicker: 'Tonnage per session',
    tonnageNote: 'Weight × reps added up across all sets.',
    history: 'History',
    noHistory: 'You have not logged this exercise yet.',
    colDate: 'Date',
    colSets: 'Sets',
    needTwo: 'At least two entries are needed to draw the trend.',

    bodyTitle: 'Weight and waist',
    bodyNote: 'Compare <strong>weekly averages</strong>, never single days. Waist is the best indicator: if it is going down you are on track even when the scale stalls.',
    fieldWeight: 'Body weight (kg)',
    fieldWaist: 'Waist (cm) — optional',
    saveToday: 'Save today’s',
    evolution: 'Trend',
    legendWeight: 'Weight (kg)',
    legendWaist: 'Waist (cm)',
    records: 'Entries',
    needOneValue: 'Enter at least one value',
    saved: 'Saved',

    dietTitle: 'Diet',
    kcalDay: 'kcal/day',
    gProtein: 'g protein',
    gCarbs: 'g carbs',
    gFat: 'g fat',
    proteinLabel: 'Protein:',
    sampleDay: 'Sample day',
    sampleSums: 'Adds up to <strong>{0} kcal</strong> and <strong>{1} g</strong> of protein, for about <strong>€{2}</strong> a day.',
    sampleFits: 'It matches your target.',
    sampleOver: 'It comes in {0} kcal over: adjust with the rice, pasta or bread portion.',
    sampleUnder: 'It comes in {0} kcal under: adjust with the rice, pasta or bread portion.',
    shoppingTitle: 'Shopping list',
    weekPlanKicker: 'Your week',
    weekPlanNote: 'Lunch and dinner are what rotate. Breakfast, mid-morning, the pre-gym shake and the bedtime serving are always the same: one less thing to decide.',
    shoppingNote: '{0} of {1} items already in the trolley. Saved on this phone, not synced.',
    shoppingTimes: '× {0} this week',
    shoppingClear: 'Clear the list',
    allRecipes: 'All recipes',
    catBreakfast: 'Breakfasts',
    catLunch: 'Lunches',
    catDinner: 'Dinners',
    catSnack: 'Snacks',
    ingredients: 'Ingredients',
    preparation: 'Method',
    halfPortion: '(half portion)',
    minShort: 'min',
    dietDisclaimer: 'Calories are estimates from standard food tables and prices are indicative: they change every season. They are there to hit the target within 5-10 %, which is what matters.',

    settingsTitle: 'Settings',
    language: 'Language',
    syncKicker: 'Sync',
    syncLocal: 'Local only — Supabase not configured',
    syncPending: '{0} entr(ies) waiting to upload',
    syncOk: 'Everything synced',
    lastUpload: 'Last upload: {0}',
    btnSync: 'Sync now',
    btnPull: 'Restore from cloud',
    btnExport: 'Download backup',
    btnImport: 'Restore backup',
    noCloudWarn: 'Without Supabase configured the data lives only on this phone. <strong>Safari can wipe it if you do not open the app for ~7 days.</strong> Download a backup now and then.',
    syncing: 'Syncing…',
    syncedN: '{0} entr(ies) uploaded',
    nothingPending: 'Nothing pending',
    searchingCloud: 'Checking the cloud…',
    recovered: 'Restored {0} sets and {1} weigh-ins',
    nothingToRecover: 'There was nothing new to restore',
    errorPrefix: 'Error: {0}',
    restored: 'Backup restored',
    badFile: 'Invalid file',
    mesoKicker: 'Mesocycle',
    blockN: 'Block {0}',
    blockCurrent: 'in progress, week {0} of 4',
    blockToday: 'today',
    blockRange: '{0} → {1} · {2} sessions, {3} sets',
    blockStarts1: 'You are already in week 1. Your first set will set the start date.',
    blockAutoNote: 'Blocks count themselves from your first session: four weeks each, and the next one starts with the first session you log afterwards. Nothing to configure, and nothing from the previous block is deleted.',
    blockNewTitle: 'Block {0} under way.',
    blockNewBody: 'Block {0} closed: {1} to {2}, {3} sessions and {4} sets. It is all still in Settings. The new one started with your session on {5}.',
    blockOk: 'Got it',
    account: 'Account',
    logout: 'Sign out',
    timerNote: '<strong>About the timer:</strong> the count stays correct even if you lock the phone, but <strong>it does not ring on its own</strong>. iOS does not allow reliable background alarms without push notifications.',
    verChecking: 'checking…',
    verUpToDate: 'up to date',
    verAvailable: 'v{0} is available',
    verOffline: 'offline',
    updateNew: 'A new version is available <strong>(v{0})</strong>. You have v{1}.',
    updateBtn: 'Update',
    updating: 'Updating…',

    sugStart: 'First time: the plan’s starting load. Adjust it until the target RIR is real.',
    sugHoldReps: 'You have not reached {0} on every set yet: repeat the weight and try to add 1 rep.',
    sugHoldRir: 'You hit the top of the range but with no margin (RIR below {0}): hold this weight one more session.',
    sugLoadBw: 'Top of the range completed: add 2.5 kg of load or go up to {0} reps.',
    sugLoadPlain: 'Top of the range completed.',
    sugUp: 'You completed {0} reps on every set with margin, so go up to {1} kg.',
    sugUpAssist: 'You completed {0} reps on every set with margin, so drop the assistance to {1} kg.',
    storageError: 'Could not save. Private browsing or storage full?',
    recoveredFromCloud: 'Restored {0} entries from the cloud',
  },

  slots: {
    'Desayuno': 'Breakfast',
    'Media mañana': 'Mid-morning',
    'Comida': 'Lunch',
    'Merienda': 'Afternoon snack',
    'Post-entreno': 'Post-workout',
    'Media tarde': 'Late afternoon',
    'Cena': 'Dinner',
    'Antes de dormir': 'Before bed',
  },

  users: {
    jan: { subtitle: "Five days · beginner · build muscle" },
    anna: { subtitle: 'Upper–lower · 4 days · glutes and legs priority' },
    david: { subtitle: 'Recomposition · 4 days · upper body priority' },
  },

  targets: {
    jan: {
      estrategia: 'Surplus to grow and build muscle',
      detalle: 'At 52 kg for 177 cm you are underweight, and on top of that you said you are in a deficit. That is exactly the opposite of what you need: at 15 and with 0-6 months in the gym, muscle does not come from training more, it comes from eating more. Target: +0.3-0.5 kg a month. If the scale has not moved in 3 weeks, it is not the routine — you are eating too little.',
      proteinaNota: 'Your 115 g are the floor. With the protein powder you already take you get there easily, but what you are really missing is calories: rice cream and rice, pasta and bread are your allies here.',
    },
    anna: {
      estrategia: 'Slight surplus to build muscle',
      detalle: 'At 52 kg and 15 % body fat there is nothing to cut: without eating above maintenance no new tissue gets built. The goal is +0.2-0.4 kg a month, no more — beyond that what you gain is fat.',
      proteinaNota: 'Your floor is 110 g. Going over is not a problem; falling short is.',
    },
    david: {
      estrategia: 'Moderate deficit for recomposition',
      detalle: 'At 27 % body fat with 3-4 years of training, you can gain muscle and lose fat at the same time, but only by eating below maintenance. Target: −0.5 to −0.7 kg per week.',
      proteinaNota: 'The 190 g are what protects your lean mass in a deficit, and it is also what fills you up most.',
    },
  },

  days: {
    'j-pecho-a': { name: "Chest, shoulders and triceps", subtitle: "Push · session A", warmup: "5 min bike or elliptical · band shoulder mobility (20 external rotations) · 15 very light face pulls. On the dumbbell bench press: one set of 12 with a very light weight before your first real set. You are 15 and new to this: technique comes before kilos, always." },
    'j-espalda-a': { name: "Back and biceps", subtitle: "Pull · session A", warmup: "5 min rowing · 10 passive bar hangs of 10 s · 20 band rows. On the machine row: 2 ramp-up sets, one at 50 % and one at 70 %." },
    'j-pierna': { name: "Legs", subtitle: "Full lower body", warmup: "5 min bike · ankle mobility against the wall (10 per side) · 90/90 hip · 15 glute bridges. On the squat: empty bar × 10, 50 % × 5 and 70 % × 3." },
    'j-pecho-b': { name: "Chest, shoulders and triceps", subtitle: "Push · session B", warmup: "5 min rowing · thoracic mobility · 20 band external rotations · 15 light face pulls. Same session as Monday: the weights you logged then are today's starting point." },
    'j-espalda-b': { name: "Arms, forearms and core", subtitle: "Accessories · with calves and core", warmup: "5 min bike · elbow and wrist mobility (10 circles each way) · 15 wrist curls with no weight. You already trained your back on Tuesday: today is for what the big sessions leave short." },
    'a-torso-a': { name: 'Upper A', subtitle: 'Vertical back, shoulders and arms', warmup: '5 min easy rowing or elliptical · thoracic spine mobility (cat-camel, rotations) · 20 band external rotations · shoulder dislocations with a stick. On the pulldown: 2 ramp-up sets at 50 % and 75 % of working weight, 5 reps each.' },
    'a-pierna-a': { name: "Quads and glutes", subtitle: "Knee dominant", warmup: "5 min bike · ankle mobility against the wall (10 per side) · 90/90 hip · 15 glute bridges and 15 band lateral walks. On the squat: empty bar × 10, then 50 % × 5, 70 % × 3 and 85 % × 1." },
    'a-torso-b': { name: "Upper B", subtitle: "Horizontal back, shoulders and arms · short session", warmup: "5 min rowing · thoracic mobility on your knees · 20 light face pulls · 10 passive bar hangs (5-10 s each). On the row: 1 ramp-up set at 60 % × 8." },
    'a-pierna-b': { name: "Glutes and hips", subtitle: "The session that matters most: that is why it goes first", warmup: "5 min bike · 90/90 hip and psoas stretch · 20 banded glute bridges · 15 standing band abductions. On the hip thrust: empty bar × 12 and another at 60 % × 8." },
    'd-empuje': { name: 'Upper A · Push', subtitle: 'Chest, shoulders and triceps', warmup: '5 min rowing or elliptical · thoracic mobility on a foam roller · 20 band external rotations · 15 light face pulls. On the bench: empty bar × 12, then 50 % × 8, 70 % × 5 and 85 % × 2.' },
    'd-tiron': { name: 'Upper B · Pull', subtitle: 'Back, biceps and traps', warmup: '5 min bike · 10 passive bar hangs of 10 s · 20 stick dislocations · 15 band rows. On the barbell row: 2 ramp-up sets at 50 % and 75 %, 6 reps each.' },
    'd-pierna': { name: 'Legs + core', subtitle: 'Efficient maintenance', warmup: '5 min bike · ankle mobility against the wall (10 per side) · 90/90 hip and psoas stretch · 15 glute bridges. On the squat: empty bar × 10, 50 % × 5, 70 % × 3, 85 % × 1.' },
    'd-completo': { name: 'Upper C · Full', subtitle: 'Upper chest, back and shoulders', warmup: '5 min rowing · thoracic mobility on a foam roller · 20 band external rotations · 15 light face pulls. On the incline press: empty bar × 12, 55 % × 8 and 75 % × 4.' },
  },

  ex: {
    'a-zancada-caminando': { name: "Walking lunge with dumbbells", cue: "Long step, back knee towards the floor, push through the front heel. 10-12 steps per leg. It needs two dumbbells and a corridor: the glute work you can always do even when the gym is packed." },
    'a-hip-thrust-alto': { name: "Machine hip thrust (high reps)", cue: "Second glute dose of the week. Same movement as Monday but lighter and with more reps: squeeze 2 s at the top on every one." },
    'j-dead-bug': { name: 'Dead bug', cue: 'On your back, lower opposite arm and leg without letting your lower back come off the floor. 10 per side, slow.' },
    'j-press-banca': { name: "Barbell bench press", cue: "Shoulder blades retracted, elbows at 45-60°. Down in 2 s and touch the chest without bouncing. Derived from your 90 × 2: start at 75 kg." },
    'j-press-inclinado-mancuernas': { name: "Incline dumbbell press (30°)", cue: "Upper chest: the area that most defines how the torso looks with a shirt on." },
    'j-press-hombro-mancuernas': { name: "Seated dumbbell shoulder press", cue: "Backrest at 85°. Higher reps than Monday to add volume without repeating the fatigue." },
    'j-aperturas-polea': { name: "Cable chest fly (crossover)", cue: "Superset with the next one. Pulleys at shoulder height, bring your hands together in front and squeeze 1 s." },
    'j-triceps-cuerda': { name: "Rope triceps pushdown", cue: "Elbows pinned to your sides and still. Spread the rope at the end of the range." },
    'j-press-frances': { name: "EZ-bar skull crusher", cue: "Superset with the previous one. Works the long head of the triceps." },
    'j-plancha': { name: "Front plank", cue: "Glutes squeezed and pelvis tucked. Better 30 s done well than 60 s with the hips sagging." },
    'j-jalon-neutro': { name: "Lat pulldown, neutral grip", cue: "The second grip, with the triangle handle and palms facing each other. Chest tall, elbows towards your ribs and a 1 s pause at the bottom." },
    'j-face-pull': { name: "High cable face pull", cue: "Elbows high, external rotation at the end. The best antidote to a programmer’s forward shoulder." },
    'j-curl-barra-z': { name: "EZ-bar biceps curl", cue: "Superset with the next one. Elbows still by your torso, no hip swing." },
    'j-curl-martillo': { name: "Hammer curl", cue: "Palms facing: works the brachialis and thickens the arm. Elbows still, next to your torso." },
    'j-rdl': { name: "Barbell Romanian deadlift", cue: "Hips back, bar grazing your thigh. Stop when you lose the lumbar curve." },
    'j-prensa': { name: "Leg press 45°", cue: "Feet mid-height. Do not lock the knees at the top; controlled 2 s descent." },
    'j-femoral-tumbado': { name: "Lying leg curl", cue: "Hips pinned to the bench, slow 3 s eccentric. Offsets the hours of shortened hamstrings in the chair." },
    'j-extension-cuadriceps': { name: "Leg extension", cue: "1 s pause at the top. Last set with 2-3 partial reps." },
    'j-gemelo-pie': { name: "Standing calf raise", cue: "Full range: stretch 2 s at the bottom, squeeze 1 s at the top." },
    'j-rueda-abdominal': { name: "Ab wheel or front plank", cue: "Pelvis tucked, do not let the hips drop. This does not burn belly fat: the deficit does that." },
    'j-press-inclinado-barra': { name: "Incline barbell press (30°)", cue: "Upper chest is what changes the shape of your torso the most. Bench at 30°, no steeper: above that it turns into a shoulder press." },
    'j-press-militar': { name: "Standing barbell overhead press", cue: "Glutes and abs braced so you do not arch. Head back as the bar passes." },
    'j-fondos': { name: "Parallel bar dips", cue: "Torso leaning slightly forward to load the chest. If you cannot reach 8, use the assisted machine." },
    'j-encogimientos': { name: "Dumbbell shrugs", cue: "Straight up, no rolling. 1 s pause at the top." },
    'j-remo-mancuerna': { name: "Single-arm dumbbell row", cue: "Knee and hand on the bench. Long range and full stretch at the bottom. 10-12 per arm." },
    'j-jalon-prono': { name: "Lat pulldown, wide overhand grip", cue: "The first of the three grips. Wide and palms forward: this is the one that widens your back seen from the front." },
    'j-curl-inclinado': { name: "Incline bench biceps curl", cue: "Arm behind the torso, full stretch at the bottom." },
    'j-gemelo-sentado': { name: "Seated calf raise", cue: "Works the soleus. High reps, slow tempo." },
    'j-elevacion-piernas': { name: "Lying leg raise on the floor", cue: "Hands under your glutes, lower back pressed to the floor. Only lower your legs as far as you can keep it pressed." },
    'j-plancha-lateral': { name: "Side plank", cue: "Forearm support, hips high and in line. 20-30 s per side, alternating." },
    'j-laterales': { name: "Dumbbell lateral raises", cue: "Up to horizontal and down over 3 s. Light weight: if you have to swing, it is too heavy." },
    'j-dominada-asistida': { name: "Assisted pull-up", cue: "Machine or band. More assistance means easier. The goal for the block is to lower the assistance, not just add reps." },
    'j-remo-barra': { name: "Barbell row at 45°", cue: "Torso rigid and pull towards your navel. If your lower back rounds, drop the weight: at 15 that is not negotiable." },
    'j-sentadilla': { name: "Back squat", cue: "Weeks 1 and 2 with the empty bar until the pattern is automatic. Depth to parallel, knees tracking over your toes." },
    'j-laterales-polea': { name: "Cable lateral raises", cue: "On the cable the tension does not disappear at the bottom, which is where a dumbbell stops weighing anything. Raise to horizontal and lower over 3 s: if you have to swing, the weight is too heavy." },
    'j-deltoide-polea': { name: "Cable rear delt fly", cue: "Arm crossed in front of your body, open out and back with the elbow almost straight." },
    'j-triceps-barra': { name: "Straight-bar triceps pushdown", cue: "Same movement as Monday but with a bar instead of the rope: different grip, different stimulus." },
    'j-rdl-mancuernas': { name: "Dumbbell Romanian deadlift", cue: "Complements Wednesday’s legs without loading the lower back like the barbell. Hips back, flat back." },
    'j-granjero': { name: "Farmer’s walk with dumbbells", cue: "Your forearm work. Shoulders back, core braced and short steps. Grip is what limits rows and pull-ups, so this makes you stronger at everything else." },
    'j-press-banca-mancuernas': { name: "Dumbbell bench press", cue: "Shoulder blades back and down, elbows at 45°. With dumbbells each arm works on its own, so start light: lower until the dumbbells are level with your chest, without forcing the shoulder." },
    'j-peck-deck': { name: "Pec deck", cue: "The machine guides the path, so it is the easiest way to learn to squeeze the chest. Back flat against the pad, close slowly and squeeze for 1 s in the middle." },
    'j-remo-maquina': { name: "Seated machine row", cue: "The chest pad or a braced back does the job your lower back used to do on the barbell row, so here you can go heavier without the risk. Pull towards your navel and squeeze the shoulder blades." },
    'j-jalon-supino': { name: "Lat pulldown, underhand grip", cue: "The third grip: narrow, palms facing you. It brings in the most biceps, so expect to handle more weight." },
    'j-curl-sentado': { name: "Seated dumbbell curl", cue: "Sitting upright you cannot help yourself with your hips, so the biceps works alone. That is why it comes last and light." },
    'j-gemelo-mancuerna': { name: "Single-leg dumbbell calf raise", cue: "No machine: a dumbbell in the hand of the working side, the ball of your foot on a step or a plate and the other leg tucked up. Drop the heel as far as it goes and rise all the way up. Hold on to something so you keep your balance." },
    'j-curl-muneca': { name: "Barbell wrist curl", cue: "Seated, forearms resting on your thighs and hands past your knees, palms up. Let the bar roll down to your fingers and close it as you lift. Light weight and high reps: the forearm takes a lot." },
    // --- Anna, Upper A
    'a-jalon-prono': { name: 'Lat pulldown, wide overhand grip', cue: 'Chest tall, pull with your elbows towards your ribs. No swinging.' },
    'a-press-banca-mancuernas': { name: "Flat dumbbell bench press", cue: "Five sessions stuck at 12 kg logging RIR 4: you had margin to spare, not weight. Start at 13 and chase a real RIR 2." },
    'a-press-militar-mancuernas': { name: "Seated dumbbell shoulder press", cue: "Backrest at 80-85°, ribs down so you do not arch. You closed the block at 10 kg per hand, hitting the top of the range." },
    'a-laterales': { name: "Dumbbell lateral raises", cue: "Raise to horizontal, lower in 2-3 s. Zero hip drive. You dropped from 7 to 5 kg during the block: stay at 5 and only go up when 15 come out clean." },
    'a-face-pull': { name: "High cable face pull", cue: "Elbows high and external rotation at the end: rear delt plus rotators. It is what offsets the hours of forward shoulder. Normal set with its own rest, no longer chained to anything." },
    'a-curl-inclinado': { name: 'Incline bench biceps curl', cue: 'Arm behind the torso, full stretch at the bottom.' },
    'a-remo-mancuerna': { name: "Single-arm dumbbell row", cue: "One hand and one knee on the bench. 10-12 per arm. One arm at a time works each side on its own and the core resisting rotation." },
    'a-press-frances': { name: "Dumbbell skull crusher", cue: "Lying on the bench, lower the dumbbells towards your forehead with the elbows still. The triceps works stretched, which is where it grows most." },
    'a-plancha': { name: 'Front plank', cue: 'Glutes squeezed, pelvis tucked. Quality over duration.' },
    // --- Anna, Legs A
    'a-sentadilla': { name: "Back squat", cue: "From 60 to 80 kg in five weeks, the best progress of your whole block. All 4 sets at the SAME weight: ramping inside the session inflates the number, not the volume." },
    'a-rdl': { name: "Barbell Romanian deadlift", cue: "Hips back, bar grazing your thigh. Stop when you lose the lumbar curve. You finished at 60 × 10 with RIR 2: pick it up there." },
    'a-prensa': { name: 'Leg press 45°, feet mid-height', cue: 'Do not lock the knees at the top. Controlled 2 s descent.' },
    'a-femoral-tumbada': { name: 'Lying leg curl', cue: 'Hips pinned to the bench; slow 3 s eccentric.' },
    'a-extension-cuadriceps': { name: "Leg extension", cue: "1 s pause at the top. You logged three sets in a row at RIR 5: that is warm-up weight. At 35 kg you should just barely reach 15." },
    'a-gemelo-pie': { name: 'Standing calf raise', cue: 'Full range: stretch 2 s at the bottom, squeeze 1 s at the top.' },
    'a-plancha-lateral': { name: 'Side plank', cue: 'Forearm support, hips high and in line. Alternate sides.' },
    // --- Anna, Upper B
    'a-dominada-asistida': { name: "Assisted pull-up machine", cue: "More assistance kilos means easier. Three sessions stuck at 35 kg of assistance: the goal this block is to get under 30." },
    'a-press-inclinado-mancuernas': { name: "Incline dumbbell press (30°)", cue: "From 8 to 12 kg per hand in the block, +50 % e1RM: your best pressing exercise. Carry on from 12." },
    'a-remo-maquina': { name: "Seated machine row", cue: "Chest against the pad if the machine has one. Pull with your elbows, 1 s pause with the shoulder blades together and release slowly." },
    'a-lateral-polea': { name: "Single-arm cable lateral raise", cue: "One arm at a time, low pulley crossed behind your body. Constant tension at the bottom too, which the dumbbell on Tuesday does not give you." },
    'a-deltoide-polea': { name: "Single-arm cable rear delt fly", cue: "Pulley at shoulder height, grab the handle with the arm crossed in front and open out and back. Elbow almost straight. It is the exercise that went up the most in your whole block (+56 %)." },
    'a-pullover': { name: 'High cable pullover', cue: 'Arms almost straight, isolates the lat without involving the biceps.' },
    'a-curl-martillo': { name: 'Hammer curl', cue: 'Palms facing each other. Works the brachialis: thickens the arm.' },
    'a-triceps-barra': { name: "Straight-bar triceps pushdown", cue: "Elbows pinned to your sides and still. Bar grip instead of rope to change the stimulus from Tuesday. With full rest now, no longer chained to the curl." },
    'a-crunch-piernas': { name: "Lying leg raise on the floor", cue: "Hands under your glutes, lower back pinned to the floor. Only lower your legs as far as you can keep it pinned. Last block you never got to it once: now it sits in a session you actually finish." },
    // --- Anna, Legs B
    'a-hip-thrust': { name: "Machine hip thrust (plate loaded)", cue: "Back against the pad, cushion over your hips. Chin tucked and a 1 s pause at the top without over-arching. You only did this once last block: now it opens Monday and comes back Thursday with higher reps." },
    'a-bulgara': { name: "Bulgarian split squat with dumbbells", cue: "You only did it once in the whole block and already hit the top of the range: start at 8 kg per hand. 8-10 per leg." },
    'a-femoral-sentada': { name: 'Lying leg curl', cue: 'Same exercise as Tuesday but with more reps. Hips pinned to the bench and a slow 3 s eccentric.' },
    'a-prensa-alta': { name: "Leg press, feet high and wide", cue: "Emphasises glutes and hamstrings. Deep range without letting your lower back peel off. If the press is taken, do one extra set of lunges and move on." },
    'a-abduccion': { name: "Hip abduction machine", cue: "Torso slightly forward. 1 s pause at full opening. You were at 45 × 15 with RIR 2: start at 55." },
    'a-gemelo-sentada': { name: 'Seated calf raise', cue: 'Works the soleus. High reps, slow tempo.' },
    'a-granjero': { name: 'Farmer’s walk with dumbbells', cue: 'Shoulders back, core braced and short steps. Do not let the weight tip you to one side: that is exactly what you are training. You started at 10 kg per hand; go up once you can hold the full 45 s without losing posture.' },
    'a-dead-bug': { name: 'Dead bug', cue: 'Lower opposite arm and leg without letting your lower back come off the floor. 10 per side.' },

    // --- David, Push
    'd-press-banca': { name: "Barbell bench press", cue: "Four sessions stuck at 80 kg with reps dropping from 6 to 5: that is not a plateau, that is too much weight. Drop to 72.5 and do all 4 sets at the same weight until you reach 4 × 8. You will be back at 80 with real volume behind it." },
    'd-press-militar': { name: "Standing barbell overhead press", cue: "Glutes and abs tight so you do not arch. At 40 kg you always stopped at 8 reps and never hit the top of the range: from 37.5 you do reach 10 and progression unlocks." },
    'd-press-inclinado-mancuernas': { name: "Incline dumbbell press (30°)", cue: "Upper chest: what most defines how the torso looks dressed. Four sessions at 28 kg without moving, so start at 26 and aim to close all 4 sets inside the range. One set more than last block." },
    'd-fondos': { name: "Parallel bar dips", cue: "Torso tilted slightly forward to load the chest. They come after the presses because with the bench busy they are the push that is always free. If you cannot make 8, use the assisted machine." },
    'd-laterales-polea': { name: "Cable lateral raises", cue: "Raise to horizontal, lower in 3 s. From 5 to 7.5 kg in the block, +50 %: one of the few upper-body lifts that did progress. One arm at a time or both on a crossed low pulley." },
    'd-triceps-cuerda': { name: "Rope triceps pushdown", cue: "Elbows pinned to your sides, spread the rope at the end. Normal set with its own minute of rest: no longer chained to the skull crusher." },
    'd-press-frances': { name: "EZ-bar skull crusher", cue: "Works the long head of the triceps, the part that fills out the back of the arm. You finished at 25 × 12." },
    'd-plancha': { name: 'Front plank', cue: 'Glutes squeezed and pelvis tucked. Better 30 s done well than 60 s with the hips sagging.' },
    // --- David, Pull
    'd-dominadas': { name: "Pull-ups (overhand grip)", cue: "Reps fell from 7 to 5 during the block: too many sets at RIR 1. Drop to 3 sets and do them fresh. 3 s eccentric. Once you hit 3 × 8 clean, add 2.5 kg." },
    'd-remo-barra': { name: "Barbell row at 45°", cue: "Torso solid, pull towards your navel. If your lower back rounds, drop the weight: that one is not negotiable. You finished at 70 × 10." },
    'd-jalon': { name: 'Lat pulldown, neutral grip', cue: 'Chest tall, elbows towards your ribs. 1 s pause at the bottom.' },
    'd-remo-supino': { name: "Seated cable row, underhand grip", cue: "The supinated grip loads the lower lats more. 1 s pause, no leaning back. You reached 50 × 12 hitting the top: start there." },
    'd-face-pull': { name: "High cable face pull", cue: "Elbows high, external rotation at the end. The best antidote to forward shoulder. Four sessions at 25 × 15 without moving: time to close the 20 reps and go up." },
    'd-encogimientos': { name: "Dumbbell shrugs", cue: "Straight up, no rolling. 1 s pause at the top. From 40 to 50 kg per hand in four sessions: it earns an extra set for how well it responds." },
    'd-curl-barra-z': { name: "EZ-bar biceps curl", cue: "Elbows still beside your torso, no hip swing. At 30 kg you only got 7 reps and ended up dropping to 25: stay at 25 and gain a set. Biceps was among the weakest of the block." },
    'd-curl-martillo': { name: "Hammer curl", cue: "Palms facing: works the brachialis, which is what widens the arm from the side. Four sets now, and with its own rest: no longer chained to the EZ curl." },
    'd-plancha-lateral': { name: 'Side plank', cue: 'Forearm support, hips high and in line. 20-30 s per side, alternating.' },
    // --- David, Legs
    'd-sentadilla': { name: "Back squat", cue: "From 90 to 120 kg in five weeks, but getting there by ramping inside the session at RIR 1: that is a daily max, not volume. 4 straight sets at 105 and go up between sessions, not within them. Legs are maintenance; you want the recovery for your upper body." },
    'd-rdl': { name: "Barbell Romanian deadlift", cue: "Hips back, bar grazing your thigh. Stop when you lose the lumbar curve. You finished at 80 × 8." },
    'd-prensa': { name: "Leg press 45°", cue: "Feet at mid height, 2 s controlled descent. You ended at 240 × 10 with RIR 0-1, more than a maintenance day needs: 220 at RIR 2 and all 3 sets at the same weight." },
    'd-femoral-sentado': { name: "Lying leg curl", cue: "Hips pinned to the bench, slow 3 s eccentric. Offsets the hours of shortened hamstrings in a chair. You finished at 50 × 12." },
    'd-gemelo-pie': { name: "Standing calf raise", cue: "Full range: stretch 2 s at the bottom, squeeze 1 s at the top. Four sessions at 120 × 15 hitting the top: time to go up." },
    'd-rueda-abdominal': { name: "Ab wheel or front plank", cue: "Pelvis tucked, do not let the hips drop. This does not burn belly fat: the deficit does, and you only know the deficit if you weigh yourself." },
    'd-granjero': { name: "Farmer’s walk with dumbbells", cue: "Shoulders back, abs tight, short steps. It is the finisher of the day, 2 sets is plenty. Go up when you hold the 45 s without falling apart." },
    // --- David, Full
    'd-press-inclinado-barra': { name: "Incline barbell press (30°)", cue: "The best effort-to-visible-result ratio in your case. You only did it twice in the whole block because Friday kept getting dropped: this block it does not." },
    'd-remo-mancuerna': { name: "Single-arm dumbbell row", cue: "Knee and hand on the bench. Long range and full stretch at the bottom. 10-12 per arm. You only need one dumbbell and a bench: perfect for September." },
    'd-press-hombro-mancuernas': { name: "Seated dumbbell shoulder press", cue: "Backrest at 85°. You logged RIR 0 twice here: that is failure, not RIR 2. Stay at 22 and leave a rep or two in the tank." },
    'd-pullover': { name: "High cable pullover", cue: "Arms almost straight: isolates the lats without the biceps. It is what widens the back from the front. You finished at 25 × 15 hitting the top." },
    'd-aperturas-polea': { name: "Cable chest fly (crossover)", cue: "Pulleys at shoulder height, bring your hands together and squeeze 1 s. With full rest now: no longer chained to the lateral raises." },
    'd-laterales-mancuernas': { name: "Dumbbell lateral raises", cue: "At 12 kg you stopped at 10 reps with RIR 0: below the range and over the weight. Drop to 10 kg, do 4 sets of 12-15 clean and that is when the shoulder grows." },
    'd-pajaros': { name: 'Bent-over dumbbell rear delt fly', cue: 'Sitting on the edge of the bench, chest towards your thighs. Open your arms back with elbows almost straight. Light weight: feel matters more than kilos here.' },
    'd-dead-bug': { name: 'Dead bug', cue: 'On your back, lower opposite arm and leg without letting your lower back come off the floor. 10 per side, slow.' },
  },

  meals: {
    'queso-batido-proteina': { name: 'Quark with protein powder, oats and banana', ingredients: ['250 g fat-free quark', '30 g chocolate protein powder', '50 g rolled oats', '1 banana'], steps: ['Mix the quark with the protein powder until there are no lumps.', 'Add the oats and the sliced banana.', 'Make it the night before in a tub: the oats soften and in the morning it takes 30 seconds.'], tip: '52 g of protein in three minutes for 1.55 €. It is the best protein-per-minute-per-euro meal on the list, which is why it opens a day where you only have twenty minutes.' },
    'avena-yogur': { name: 'Protein yoghurt with oats, banana and peanut butter', ingredients: ['1 natural protein yoghurt (200 g)', '60 g rolled oats', '1 banana', '15 g peanut butter', 'Cinnamon'], steps: ['Put the oats in a bowl and cover with the yoghurt.', 'Slice the banana on top and add the peanut butter.', 'If you make it the night before, the oats soften and it eats better.'] },
    'tortilla-pavo': { name: '3-egg omelette with turkey and bread', ingredients: ['3 eggs', '60 g sliced turkey', '2 slices of wholemeal bread', 'Salt and olive oil'], steps: ['Beat the eggs with the chopped turkey and a pinch of salt.', 'Cook in the pan with a splash of oil, 3-4 min.', 'Toast the bread and serve.'] },
    'batido-avena': { name: 'Oat, milk, banana and cocoa shake', ingredients: ['350 ml whole milk', '50 g rolled oats', '1 banana', '1 tbsp pure cocoa powder', 'Optional: 1 scoop of protein'], steps: ['Everything in the blender, 30 seconds.', 'This is the option for rushed mornings: drink it on the way.'] },
    'tostadas-huevo': { name: 'Toast with egg and avocado', ingredients: ['2 slices of wholemeal bread', '2 eggs', '1/2 avocado', 'Salt, pepper and olive oil'], steps: ['Toast the bread and mash the avocado on top.', 'Fry the eggs and put them on top.', 'Salt, pepper and done.'] },
    'arroz-pollo': { name: 'Rice with chicken and stir-fried vegetables', ingredients: ['100 g basmati rice (dry)', '180 g chicken breast fillets', '200 g frozen stir-fry vegetables', 'Soy sauce', 'Olive oil'], steps: ['Boil the rice, 10-12 min.', 'Meanwhile, stir-fry the chopped chicken with a little oil.', 'Add the frozen vegetables straight from the bag and stir-fry 5 min more.', 'Mix everything with the rice and a splash of soy.'], tip: 'Cook rice and chicken for 3 days at once: the difference between sticking to the diet and not usually comes down to having the food already made.' },
    'pasta-atun': { name: 'Pasta with tuna and tomato', ingredients: ['100 g pasta (dry)', '2 tins of tuna in brine', '200 g tomato sauce or passata', 'Garlic powder and oregano'], steps: ['Boil the pasta.', 'Heat the tomato with the drained tuna, garlic and oregano, 5 min.', 'Mix.'] },
    'lentejas-huevo': { name: 'Tinned lentils with rice and egg', ingredients: ['1 tin of cooked lentils (400 g)', '60 g rice (dry)', '2 eggs', 'Paprika and olive oil'], steps: ['Rinse the lentils and heat them with a little paprika.', 'Boil the rice and the eggs (10 min for the eggs).', 'All together on the plate.'], tip: 'About the cheapest thing you will eat with this much protein.' },
    'pollo-boniato': { name: 'Roast chicken with sweet potato and salad', ingredients: ['200 g chicken breast', '250 g sweet potato', 'Bag of salad', 'Spices, salt and olive oil'], steps: ['Cut the sweet potato into wedges, oil and salt, oven at 200 °C, 25 min.', 'After 10 min add the spiced chicken to the same tray.', 'Serve with the dressed salad.'], tip: 'Make triple: it is the same half hour of oven time and it sorts three meals.' },
    'wok-ternera': { name: 'Beef wok with noodles and vegetables', ingredients: ['180 g beef strips', '2 noodle nests', '200 g frozen stir-fry vegetables', 'Soy sauce and garlic'], steps: ['Soak the noodles as per the packet (3 min).', 'Stir-fry the beef 3 min on high heat.', 'Add the vegetables, 4 min more, and mix with the noodles and soy.'] },
    'salmon-patata': { name: 'Baked salmon with potato and broccoli', ingredients: ['180 g salmon', '250 g potato', '200 g broccoli (frozen is fine)', 'Lemon, salt and olive oil'], steps: ['Sliced potato in the oven at 200 °C, 20 min.', 'Add the salmon and broccoli, 12 min more.', 'Lemon over the top when it comes out.'], tip: 'The priciest meal on the list, but the best fats. Once a week.' },
    'revuelto-gambas': { name: 'Scrambled eggs with prawns and spinach', ingredients: ['3 eggs', '100 g frozen peeled prawns', '150 g fresh spinach', 'Garlic and olive oil'], steps: ['Fry the garlic and prawns 3 min.', 'Add the spinach until it wilts.', 'Pour in the beaten eggs and stir until set.'] },
    'merluza-verduras': { name: 'Pan-fried hake with vegetables and bread', ingredients: ['200 g frozen hake fillets', '250 g frozen mixed vegetables', '1 slice of bread', 'Lemon, garlic and oil'], steps: ['Vegetables in the microwave, 6 min.', 'Hake in the pan 4 min per side with garlic.', 'Lemon and eat.'] },
    'ensalada-completa': { name: 'Loaded salad with tuna, egg and chickpeas', ingredients: ['Bag of salad', '1 small tin of cooked chickpeas', '2 tins of tuna', '2 boiled eggs', 'Sweetcorn, oil and vinegar'], steps: ['Rinse the chickpeas.', 'Mix everything in a big bowl.', 'Dress with oil, vinegar and salt.'], tip: 'Zero cooking and it takes 8 minutes. The dinner for days when you cannot be bothered.' },
    'pollo-hummus': { name: 'Grilled chicken with hummus and pitta', ingredients: ['200 g chicken breast', '80 g hummus', '1 wholemeal pitta', 'Tomato and lettuce'], steps: ['Chicken in the pan with salt and spices, 5 min per side.', 'Warm the pitta 1 min.', 'Assemble with the hummus and the veg.'] },
    'tortilla-patata': { name: 'Quick microwave potato omelette', ingredients: ['300 g potato', '3 eggs', 'Onion (optional)', 'Salt and olive oil'], steps: ['Diced potato with a little oil, covered in the microwave for 8 min.', 'Mix with the beaten eggs and salt.', 'Microwave 3-4 min more, or set it in the pan.'] },
    'yogur-almendras': { name: 'Protein yoghurt with almonds', ingredients: ['1 protein yoghurt (200 g)', '20 g almonds'], steps: ['Nothing to cook.'] },
    'tostada-cacahuete': { name: 'Toast with peanut butter and banana', ingredients: ['2 slices of wholemeal bread', '20 g peanut butter', '1 banana'], steps: ['Toast, spread, slice the banana on top.'] },
    'batido-proteina': { name: 'Protein shake with milk', ingredients: ['1 scoop of protein powder (30 g)', '300 ml milk'], steps: ['Shake.'], tip: 'The fastest and cheapest way to add 30 g of protein when the day is running tight.' },
    'requeson-fruta': { name: 'Cottage cheese with fruit and honey', ingredients: ['200 g cottage cheese or 0 % quark', '1 piece of fruit', '1 tsp honey'], steps: ['Mix.'] },
    'atun-tostadas': { name: 'Tuna on toast', ingredients: ['2 tins of tuna in brine', '2 slices of wholemeal bread', 'Tomato and oil'], steps: ['Toast the bread, rub tomato on it and add the drained tuna.'] },
  },
};
