// English. Keys must match UI_ES in i18n.js exactly (the test checks this).
export const EN = {
  ui: {
    wd: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],

    chooserKicker: 'Training log',
    chooserTitle: 'Who is training?',

    tabHome: 'Train',
    tabDiet: 'Diet',
    tabProgress: 'Progress',
    tabSettings: 'Settings',
    back: '‹ Back',

    mesoWeek: 'Mesocycle week',
    mesoOf: 'of 5',
    rirTarget: 'Target RIR',
    hintDeload: 'Deload: same weight, half the sets and far from failure. Do not skip it.',
    hintWeek3: 'One extra set is added to the first exercise of each session.',
    hintWeek4: 'Peak week: the hardest of the block.',
    hintDefault: 'Log every set. What you do not log does not progress.',
    todayIs: 'Today is {0}',
    todayDone: ' Already done, good work.',
    restDay: 'Today is a rest day.',
    nextSession: 'Next session is <strong>{0}</strong>, {1}.',
    tomorrow: 'tomorrow',
    inDays: 'in {0} days',
    restIsPlan: 'Resting is part of the plan: that is when muscle is built.',
    neverLogged: 'Never logged',
    doneToday: 'Done today',
    yesterday: 'Yesterday',
    daysAgo: '{0} days ago',
    today: 'Today',
    trackingKicker: 'Tracking',
    bodyCard: 'Body weight and waist',

    offPlanTitle: 'This is not today’s session.',
    offPlanToday: 'According to the plan, today is <strong>{0}</strong>.',
    offPlanRest: 'Today is a rest day in your plan.',
    offPlanWarn: 'You can do it anyway and it will be logged normally, but if you keep changing the order you will end up training some muscle groups too much and others too little.',
    deloadTitle: 'Deload week.',
    deloadBody: 'Sets cut in half and RIR 4: same weight, far from failure.',
    warmup: 'Warm-up',
    colExercise: 'Exercise',
    colSetsReps: 'Sets × Reps',
    colRir: 'RIR',
    colRest: 'Rest',
    colStart: 'Start load',
    colWeight: 'Weight',
    colReps: 'Reps',
    colSecs: 'Secs',
    perHand: 'kg per hand',
    bodyweight: 'Bodyweight',
    nudgeHint: 'adjust if the real RIR does not match',
    lastTime: 'Last time · {0}',
    watchVideo: '▶ Watch real video',
    needReps: 'Enter the reps before ticking the set',
    legendRir: '<strong>RIR</strong> = reps in reserve',
    legendSuperset: '<strong>Superset</strong> = both exercises back to back with no rest',

    restLabel: 'Rest',
    restTarget: 'target {0}',
    restDone: 'Rest complete · go for the next one',
    restAdd: '+30 s',
    restSkip: 'Skip',

    summary: 'Summary',
    summaryEmpty: 'Log a few sessions and this will show which exercises are progressing, which have stalled and how much you are actually training.',
    statSessions: 'sessions in 4 weeks',
    statRising: 'exercises rising',
    statStalled: 'stalled',
    adhGood: 'Very good adherence: 3-4 sessions per week, sustained.',
    adhOk: 'Adherence is fine. One more session per week and progress shows sooner.',
    adhBad: '<strong>You are training too little</strong> for this plan: it is 4 days a week. Consistency matters more than any tweak to the routine.',
    bestProgress: 'Best progression: <strong>{0}</strong> (+{1} % over the last 3 sessions).',
    manyStalled: '<strong>{0} exercises have gone several sessions without going up.</strong> If it is across the board, it is almost always food or sleep, not the programme.',
    someStalled: 'No progress on: {0}. Try dropping the weight 5 % and building back up.',
    bodyWeightLine: 'Body weight: <strong>{0} kg</strong> ({1} kg over 4 weeks).',
    waistLine: 'Waist: <strong>{0} cm</strong> since the first entry.',
    summaryFoot: 'All of this comes from your own log. To go through it properly or share it, you can download the full history as JSON in Settings.',
    e1rmKicker: 'Estimated 1RM (Epley)',
    e1rmNote: 'It goes up even when the bar weight stays put. It is the honest metric in a calorie deficit.',
    tonnageKicker: 'Tonnage per session',
    tonnageNote: 'Weight × reps added up across all sets.',
    history: 'History',
    noHistory: 'You have not logged this exercise yet.',
    colDate: 'Date',
    colSets: 'Sets',
    needTwo: 'At least two entries are needed to draw the trend.',

    bodyTitle: 'Weight and waist',
    bodyNote: 'Compare <strong>weekly averages</strong>, never single days. Waist is the best indicator: if it is going down you are on track even when the scale stalls.',
    fieldWeight: 'Body weight (kg)',
    fieldWaist: 'Waist (cm) — optional',
    saveToday: 'Save today’s',
    evolution: 'Trend',
    legendWeight: 'Weight (kg)',
    legendWaist: 'Waist (cm)',
    records: 'Entries',
    needOneValue: 'Enter at least one value',
    saved: 'Saved',

    dietTitle: 'Diet',
    kcalDay: 'kcal/day',
    gProtein: 'g protein',
    gCarbs: 'g carbs',
    gFat: 'g fat',
    proteinLabel: 'Protein:',
    sampleDay: 'Sample day',
    sampleSums: 'Adds up to <strong>{0} kcal</strong> and <strong>{1} g</strong> of protein, for about <strong>€{2}</strong> a day.',
    sampleFits: 'It matches your target.',
    sampleOver: 'It comes in {0} kcal over: adjust with the rice, pasta or bread portion.',
    sampleUnder: 'It comes in {0} kcal under: adjust with the rice, pasta or bread portion.',
    shoppingBtn: 'See the shopping list for the day',
    shoppingCopied: 'List copied to clipboard',
    shoppingTitle: 'Shopping list',
    allRecipes: 'All recipes',
    catBreakfast: 'Breakfasts',
    catLunch: 'Lunches',
    catDinner: 'Dinners',
    catSnack: 'Snacks',
    ingredients: 'Ingredients',
    preparation: 'Method',
    halfPortion: '(half portion)',
    minShort: 'min',
    dietDisclaimer: 'Calories are estimates from standard food tables and prices are indicative: they change every season. They are there to hit the target within 5-10 %, which is what matters.',

    settingsTitle: 'Settings',
    language: 'Language',
    syncKicker: 'Sync',
    syncLocal: 'Local only — Supabase not configured',
    syncPending: '{0} entr(ies) waiting to upload',
    syncOk: 'Everything synced',
    lastUpload: 'Last upload: {0}',
    btnSync: 'Sync now',
    btnPull: 'Restore from cloud',
    btnExport: 'Download backup',
    btnImport: 'Restore backup',
    noCloudWarn: 'Without Supabase configured the data lives only on this phone. <strong>Safari can wipe it if you do not open the app for ~7 days.</strong> Download a backup now and then.',
    syncing: 'Syncing…',
    syncedN: '{0} entr(ies) uploaded',
    nothingPending: 'Nothing pending',
    searchingCloud: 'Checking the cloud…',
    recovered: 'Restored {0} sets and {1} weigh-ins',
    nothingToRecover: 'There was nothing new to restore',
    errorPrefix: 'Error: {0}',
    restored: 'Backup restored',
    badFile: 'Invalid file',
    mesoKicker: 'Mesocycle',
    mesoState: 'Week <strong>{0} of 5</strong> · started on {1}',
    mesoStart: 'Start date',
    mesoReset: 'Start a new mesocycle today',
    mesoResetDone: 'Mesocycle reset to week 1',
    account: 'Account',
    switchUser: 'Switch user',
    timerNote: '<strong>About the timer:</strong> the count stays correct even if you lock the phone, but <strong>it does not ring on its own</strong>. iOS does not allow reliable background alarms without push notifications.',
    verChecking: 'checking…',
    verUpToDate: 'up to date',
    verAvailable: 'v{0} is available',
    verOffline: 'offline',
    updateNew: 'A new version is available <strong>(v{0})</strong>. You have v{1}.',
    updateBtn: 'Update',
    updating: 'Updating…',

    sugStart: 'First time: the plan’s starting load. Adjust it until the target RIR is real.',
    sugDeload: 'Deload week: same weight, half the sets and far from failure.',
    sugHoldReps: 'You have not reached {0} on every set yet: repeat the weight and try to add 1 rep.',
    sugHoldRir: 'You hit the top of the range but with no margin (RIR below {0}): hold this weight one more session.',
    sugLoadBw: 'Top of the range completed: add 2.5 kg of load or go up to {0} reps.',
    sugLoadPlain: 'Top of the range completed.',
    sugUp: 'You completed {0} reps on every set with margin, so go up to {1} kg.',
    sugUpAssist: 'You completed {0} reps on every set with margin, so drop the assistance to {1} kg.',
    storageError: 'Could not save. Private browsing or storage full?',
    recoveredFromCloud: 'Restored {0} entries from the cloud',
  },

  slots: {
    'Desayuno': 'Breakfast',
    'Media mañana': 'Mid-morning',
    'Comida': 'Lunch',
    'Merienda': 'Afternoon snack',
    'Post-entreno': 'Post-workout',
    'Media tarde': 'Late afternoon',
    'Cena': 'Dinner',
    'Antes de dormir': 'Before bed',
  },

  users: {
    anna: { subtitle: 'Upper–lower · 4 days · build muscle' },
    david: { subtitle: 'Recomposition · 4 days · upper body priority' },
  },

  targets: {
    anna: {
      estrategia: 'Slight surplus to build muscle',
      detalle: 'At 52 kg and 15 % body fat there is nothing to cut: without eating above maintenance no new tissue gets built. The goal is +0.2-0.4 kg a month, no more — beyond that what you gain is fat.',
      proteinaNota: 'Your floor is 110 g. Going over is not a problem; falling short is.',
    },
    david: {
      estrategia: 'Moderate deficit for recomposition',
      detalle: 'At 27 % body fat with 3-4 years of training, you can gain muscle and lose fat at the same time, but only by eating below maintenance. Target: −0.5 to −0.7 kg per week.',
      proteinaNota: 'The 190 g are what protects your lean mass in a deficit, and it is also what fills you up most.',
    },
  },

  days: {
    'a-torso-a': { name: 'Upper A', subtitle: 'Vertical back, shoulders and arms', warmup: '5 min easy rowing or elliptical · thoracic spine mobility (cat-camel, rotations) · 20 band external rotations · shoulder dislocations with a stick. On the pulldown: 2 ramp-up sets at 50 % and 75 % of working weight, 5 reps each.' },
    'a-pierna-a': { name: 'Legs A', subtitle: 'Knee dominant', warmup: '5 min bike · ankle mobility against the wall (10 per side) · 90/90 hip · 15 glute bridges and 15 band lateral walks. On the squat: empty bar × 10, then 50 % × 5, 70 % × 3 and 85 % × 1.' },
    'a-torso-b': { name: 'Upper B', subtitle: 'Horizontal back, shoulders and arms', warmup: '5 min rowing · thoracic mobility on knees · 20 light face pulls · 10 passive bar hangs (5-10 s each). On the dumbbell row: 1 ramp-up set at 60 % × 8 per arm.' },
    'a-pierna-b': { name: 'Legs B', subtitle: 'Hip and glute dominant', warmup: '5 min bike · 90/90 hip and psoas stretch · 20 banded glute bridges · 15 standing band abductions. On the hip thrust: empty bar × 12 and another at 60 % × 8.' },
    'd-empuje': { name: 'Upper A · Push', subtitle: 'Chest, shoulders and triceps', warmup: '5 min rowing or elliptical · thoracic mobility on a foam roller · 20 band external rotations · 15 light face pulls. On the bench: empty bar × 12, then 50 % × 8, 70 % × 5 and 85 % × 2.' },
    'd-tiron': { name: 'Upper B · Pull', subtitle: 'Back, biceps and traps', warmup: '5 min bike · 10 passive bar hangs of 10 s · 20 stick dislocations · 15 band rows. On the barbell row: 2 ramp-up sets at 50 % and 75 %, 6 reps each.' },
    'd-pierna': { name: 'Legs + core', subtitle: 'Efficient maintenance', warmup: '5 min bike · ankle mobility against the wall (10 per side) · 90/90 hip and psoas stretch · 15 glute bridges. On the squat: empty bar × 10, 50 % × 5, 70 % × 3, 85 % × 1.' },
    'd-completo': { name: 'Upper C · Full', subtitle: 'Upper chest, back and shoulders', warmup: '5 min rowing · thoracic mobility on a foam roller · 20 band external rotations · 15 light face pulls. On the incline press: empty bar × 12, 55 % × 8 and 75 % × 4.' },
  },

  ex: {
    // --- Anna, Upper A
    'a-jalon-prono': { name: 'Lat pulldown, wide overhand grip', cue: 'Chest tall, pull with your elbows towards your ribs. No swinging.' },
    'a-press-banca-mancuernas': { name: 'Flat dumbbell bench press', cue: 'Chest maintenance. Full range, no need to chase records.' },
    'a-remo-polea-neutro': { name: 'Seated cable row, neutral grip', cue: '1 s pause at the contraction, shoulder blades back and down.' },
    'a-press-militar-mancuernas': { name: 'Seated dumbbell shoulder press', cue: 'Backrest at 80-85°, ribs down so you do not arch your lower back.' },
    'a-laterales': { name: 'Lateral raises', cue: 'Up to horizontal, down over 2-3 s. Zero hip drive.' },
    'a-face-pull': { name: 'High cable face pull', cue: 'Superset with the previous one. Elbows high, external rotation at the end. Key for your shoulder.' },
    'a-curl-inclinado': { name: 'Incline bench biceps curl', cue: 'Arm behind the torso, full stretch at the bottom.' },
    'a-triceps-cuerda': { name: 'Rope triceps pushdown', cue: 'Superset with the curl. Elbows pinned to your sides.' },
    'a-plancha': { name: 'Front plank', cue: 'Glutes squeezed, pelvis tucked. Quality over duration.' },
    // --- Anna, Legs A
    'a-sentadilla': { name: 'Back squat', cue: 'Week 1: empty bar (20 kg) until the pattern is automatic. Depth to parallel or slightly below.' },
    'a-rdl': { name: 'Barbell Romanian deadlift', cue: 'Hips back, bar grazing your thigh. Stop when you lose the lumbar curve.' },
    'a-prensa': { name: 'Leg press 45°, feet mid-height', cue: 'Do not lock the knees at the top. Controlled 2 s descent.' },
    'a-femoral-tumbada': { name: 'Lying leg curl', cue: 'Hips pinned to the bench; slow 3 s eccentric.' },
    'a-extension-cuadriceps': { name: 'Leg extension', cue: '1 s pause at the top. Last set with 2-3 partial reps.' },
    'a-gemelo-pie': { name: 'Standing calf raise', cue: 'Full range: stretch 2 s at the bottom, squeeze 1 s at the top.' },
    'a-plancha-lateral': { name: 'Side plank', cue: 'Forearm support, hips high and in line. Alternate sides.' },
    // --- Anna, Upper B
    'a-dominada-asistida': { name: 'Assisted pull-up machine', cue: 'More assistance kilos means easier. Goal for the block: bring the assistance down.' },
    'a-press-inclinado-mancuernas': { name: 'Incline dumbbell press (30°)', cue: 'Chest maintenance. 2 working sets are enough if you are short on time.' },
    'a-remo-maquina': { name: "Seated machine row", cue: "Chest against the pad if the machine has one. Pull with your elbows, 1 s pause with the shoulder blades together and release slowly." },
    'a-lateral-polea': { name: "Single-arm cable lateral raise", cue: "One arm at a time, low pulley crossed behind your body. Constant tension at the bottom of the range too, which the dumbbell does not give you." },
    'a-deltoide-polea': { name: "Single-arm cable rear delt fly", cue: "Pulley at shoulder height, grab the handle with your arm crossed in front of your body and open out and back. Elbow almost straight. Replaces the reverse pec-deck, which your gym does not have." },
    'a-pullover': { name: 'High cable pullover', cue: 'Arms almost straight, isolates the lat without involving the biceps.' },
    'a-curl-martillo': { name: 'Hammer curl', cue: 'Palms facing each other. Works the brachialis: thickens the arm.' },
    'a-triceps-barra': { name: 'Straight-bar triceps pushdown', cue: 'Superset with the curl. High pulley, elbows pinned and still. Bar grip instead of rope to change the stimulus from Monday.' },
    'a-crunch-piernas': { name: 'Lying leg raise on the floor', cue: 'Hands under your glutes, lower back pressed to the floor. Only lower your legs as far as you can keep it pressed.' },
    // --- Anna, Legs B
    'a-hip-thrust': { name: 'Machine hip thrust (plate loaded)', cue: 'Back against the pad, cushion over your hips. Chin to chest and 1 s pause at the top without over-extending the lower back. The kilos are the plates you load: each 2.5 plate per side is +5 kg.' },
    'a-bulgara': { name: 'Bulgarian split squat with dumbbells', cue: 'Start with no weight until you own the balance. 8-10 per leg.' },
    'a-femoral-sentada': { name: 'Lying leg curl', cue: 'Same exercise as Tuesday but with more reps. Hips pinned to the bench and a slow 3 s eccentric.' },
    'a-prensa-alta': { name: 'Leg press, feet high and wide', cue: 'Emphasises glutes and hamstrings. Deep range without letting the lower back lift.' },
    'a-abduccion': { name: 'Hip abduction machine', cue: 'Torso slightly forward. 1 s pause at full opening.' },
    'a-gemelo-sentada': { name: 'Seated calf raise', cue: 'Works the soleus. High reps, slow tempo.' },
    'a-granjero': { name: 'Farmer’s walk with dumbbells', cue: 'Shoulders back, core braced and short steps. Do not let the weight tip you to one side: that is exactly what you are training. You started at 10 kg per hand; go up once you can hold the full 45 s without losing posture.' },
    'a-dead-bug': { name: 'Dead bug', cue: 'Lower opposite arm and leg without letting your lower back come off the floor. 10 per side.' },

    // --- David, Push
    'd-press-banca': { name: 'Barbell bench press', cue: 'Shoulder blades retracted, elbows at 45-60°. Down in 2 s and touch the chest without bouncing. Derived from your 90 × 2: start at 75 kg.' },
    'd-press-militar': { name: 'Standing barbell overhead press', cue: 'Glutes and abs braced so you do not arch. Head back as the bar passes.' },
    'd-press-inclinado-mancuernas': { name: 'Incline dumbbell press (30°)', cue: 'Upper chest: the area that most defines how the torso looks with a shirt on.' },
    'd-fondos': { name: 'Parallel bar dips', cue: 'Torso leaning slightly forward to load the chest. If you cannot reach 8, use the assisted machine.' },
    'd-laterales-polea': { name: 'Cable lateral raises', cue: 'Up to horizontal, down over 3 s. One arm at a time or both on a crossed low pulley.' },
    'd-triceps-cuerda': { name: 'Rope triceps pushdown', cue: 'Superset with the next one. Elbows pinned to your sides, spread the rope at the end.' },
    'd-press-frances': { name: 'EZ-bar skull crusher', cue: 'Superset with the previous one. Works the long head of the triceps.' },
    'd-plancha': { name: 'Front plank', cue: 'Glutes squeezed and pelvis tucked. Better 30 s done well than 60 s with the hips sagging.' },
    // --- David, Pull
    'd-dominadas': { name: 'Pull-ups (overhand grip)', cue: 'No assistance: you already do 4 × 5. 3 s eccentric. Once you reach 4 × 8 clean, add 2.5 kg.' },
    'd-remo-barra': { name: 'Barbell row at 45°', cue: 'Torso rigid, pull towards your navel. If your lower back rounds, drop the weight: this is not negotiable.' },
    'd-jalon': { name: 'Lat pulldown, neutral grip', cue: 'Chest tall, elbows towards your ribs. 1 s pause at the bottom.' },
    'd-remo-supino': { name: 'Seated cable row, underhand grip', cue: 'The underhand grip loads the lower lat more. 1 s pause, without leaning back.' },
    'd-face-pull': { name: 'High cable face pull', cue: 'Elbows high, external rotation at the end. The best antidote to a programmer’s forward shoulder.' },
    'd-encogimientos': { name: 'Dumbbell shrugs', cue: 'Straight up, no rolling. 1 s pause at the top.' },
    'd-curl-barra-z': { name: 'EZ-bar biceps curl', cue: 'Superset with the next one. Elbows still by your torso, no hip swing.' },
    'd-curl-martillo': { name: 'Hammer curl', cue: 'Superset with the previous one. Palms facing: works the brachialis.' },
    'd-plancha-lateral': { name: 'Side plank', cue: 'Forearm support, hips high and in line. 20-30 s per side, alternating.' },
    // --- David, Legs
    'd-sentadilla': { name: 'Back squat', cue: 'No previous leg data: week 1 is pure calibration. Go up without fear if the real RIR comes out at 4.' },
    'd-rdl': { name: 'Barbell Romanian deadlift', cue: 'Hips back, bar grazing your thigh. Stop when you lose the lumbar curve.' },
    'd-prensa': { name: 'Leg press 45°', cue: 'Feet mid-height. Do not lock the knees at the top; controlled 2 s descent.' },
    'd-femoral-sentado': { name: 'Lying leg curl', cue: 'Hips pinned to the bench, slow 3 s eccentric. Offsets the hours of shortened hamstrings in the chair.' },
    'd-gemelo-pie': { name: 'Standing calf raise', cue: 'Full range: stretch 2 s at the bottom, squeeze 1 s at the top.' },
    'd-rueda-abdominal': { name: 'Ab wheel or front plank', cue: 'Pelvis tucked, do not let the hips drop. This does not burn belly fat: the deficit does that.' },
    'd-granjero': { name: 'Farmer’s walk with dumbbells', cue: 'Shoulders back, core braced and short steps. Do not let the weight tip you to one side. You tried 10 kg per hand: for your body weight that will feel light fast, go up once you hold 45 s comfortably.' },
    // --- David, Full
    'd-press-inclinado-barra': { name: 'Incline barbell press (30°)', cue: 'The best effort-to-visible-result ratio in your case. Here it is the main lift, not an accessory.' },
    'd-remo-mancuerna': { name: 'Single-arm dumbbell row', cue: 'Knee and hand on the bench. Long range and full stretch at the bottom. 10-12 per arm.' },
    'd-press-hombro-mancuernas': { name: 'Seated dumbbell shoulder press', cue: 'Backrest at 85°. Higher reps than Monday to add volume without repeating the fatigue.' },
    'd-pullover': { name: 'High cable pullover', cue: 'Arms almost straight: isolates the lat without involving the biceps. This is what widens the back from the front.' },
    'd-aperturas-polea': { name: 'Cable chest fly (crossover)', cue: 'Superset with the next one. Pulleys at shoulder height, bring your hands together in front and squeeze 1 s.' },
    'd-laterales-mancuernas': { name: 'Dumbbell lateral raises', cue: 'Superset with the previous one. Last set: 3 partial reps at the end.' },
    'd-pajaros': { name: 'Bent-over dumbbell rear delt fly', cue: 'Sitting on the edge of the bench, chest towards your thighs. Open your arms back with elbows almost straight. Light weight: feel matters more than kilos here.' },
    'd-dead-bug': { name: 'Dead bug', cue: 'On your back, lower opposite arm and leg without letting your lower back come off the floor. 10 per side, slow.' },
  },

  meals: {
    'avena-yogur': { name: 'Protein yoghurt with oats, banana and peanut butter', ingredients: ['1 natural protein yoghurt (200 g)', '60 g rolled oats', '1 banana', '15 g peanut butter', 'Cinnamon'], steps: ['Put the oats in a bowl and cover with the yoghurt.', 'Slice the banana on top and add the peanut butter.', 'If you make it the night before, the oats soften and it eats better.'] },
    'tortilla-pavo': { name: '3-egg omelette with turkey and bread', ingredients: ['3 eggs', '60 g sliced turkey', '2 slices of wholemeal bread', 'Salt and olive oil'], steps: ['Beat the eggs with the chopped turkey and a pinch of salt.', 'Cook in the pan with a splash of oil, 3-4 min.', 'Toast the bread and serve.'] },
    'batido-avena': { name: 'Oat, milk, banana and cocoa shake', ingredients: ['350 ml whole milk', '50 g rolled oats', '1 banana', '1 tbsp pure cocoa powder', 'Optional: 1 scoop of protein'], steps: ['Everything in the blender, 30 seconds.', 'This is the option for rushed mornings: drink it on the way.'] },
    'tostadas-huevo': { name: 'Toast with egg and avocado', ingredients: ['2 slices of wholemeal bread', '2 eggs', '1/2 avocado', 'Salt, pepper and olive oil'], steps: ['Toast the bread and mash the avocado on top.', 'Fry the eggs and put them on top.', 'Salt, pepper and done.'] },
    'arroz-pollo': { name: 'Rice with chicken and stir-fried vegetables', ingredients: ['100 g basmati rice (dry)', '180 g chicken breast fillets', '200 g frozen stir-fry vegetables', 'Soy sauce', 'Olive oil'], steps: ['Boil the rice, 10-12 min.', 'Meanwhile, stir-fry the chopped chicken with a little oil.', 'Add the frozen vegetables straight from the bag and stir-fry 5 min more.', 'Mix everything with the rice and a splash of soy.'], tip: 'Cook rice and chicken for 3 days at once: the difference between sticking to the diet and not usually comes down to having the food already made.' },
    'pasta-atun': { name: 'Pasta with tuna and tomato', ingredients: ['100 g pasta (dry)', '2 tins of tuna in brine', '200 g tomato sauce or passata', 'Garlic powder and oregano'], steps: ['Boil the pasta.', 'Heat the tomato with the drained tuna, garlic and oregano, 5 min.', 'Mix.'] },
    'lentejas-huevo': { name: 'Tinned lentils with rice and egg', ingredients: ['1 tin of cooked lentils (400 g)', '60 g rice (dry)', '2 eggs', 'Paprika and olive oil'], steps: ['Rinse the lentils and heat them with a little paprika.', 'Boil the rice and the eggs (10 min for the eggs).', 'All together on the plate.'], tip: 'About the cheapest thing you will eat with this much protein.' },
    'pollo-boniato': { name: 'Roast chicken with sweet potato and salad', ingredients: ['200 g chicken breast', '250 g sweet potato', 'Bag of salad', 'Spices, salt and olive oil'], steps: ['Cut the sweet potato into wedges, oil and salt, oven at 200 °C, 25 min.', 'After 10 min add the spiced chicken to the same tray.', 'Serve with the dressed salad.'], tip: 'Make triple: it is the same half hour of oven time and it sorts three meals.' },
    'wok-ternera': { name: 'Beef wok with noodles and vegetables', ingredients: ['180 g beef strips', '2 noodle nests', '200 g frozen stir-fry vegetables', 'Soy sauce and garlic'], steps: ['Soak the noodles as per the packet (3 min).', 'Stir-fry the beef 3 min on high heat.', 'Add the vegetables, 4 min more, and mix with the noodles and soy.'] },
    'salmon-patata': { name: 'Baked salmon with potato and broccoli', ingredients: ['180 g salmon', '250 g potato', '200 g broccoli (frozen is fine)', 'Lemon, salt and olive oil'], steps: ['Sliced potato in the oven at 200 °C, 20 min.', 'Add the salmon and broccoli, 12 min more.', 'Lemon over the top when it comes out.'], tip: 'The priciest meal on the list, but the best fats. Once a week.' },
    'revuelto-gambas': { name: 'Scrambled eggs with prawns and spinach', ingredients: ['3 eggs', '100 g frozen peeled prawns', '150 g fresh spinach', 'Garlic and olive oil'], steps: ['Fry the garlic and prawns 3 min.', 'Add the spinach until it wilts.', 'Pour in the beaten eggs and stir until set.'] },
    'merluza-verduras': { name: 'Pan-fried hake with vegetables and bread', ingredients: ['200 g frozen hake fillets', '250 g frozen mixed vegetables', '1 slice of bread', 'Lemon, garlic and oil'], steps: ['Vegetables in the microwave, 6 min.', 'Hake in the pan 4 min per side with garlic.', 'Lemon and eat.'] },
    'ensalada-completa': { name: 'Loaded salad with tuna, egg and chickpeas', ingredients: ['Bag of salad', '1 small tin of cooked chickpeas', '2 tins of tuna', '2 boiled eggs', 'Sweetcorn, oil and vinegar'], steps: ['Rinse the chickpeas.', 'Mix everything in a big bowl.', 'Dress with oil, vinegar and salt.'], tip: 'Zero cooking and it takes 8 minutes. The dinner for days when you cannot be bothered.' },
    'pollo-hummus': { name: 'Grilled chicken with hummus and pitta', ingredients: ['200 g chicken breast', '80 g hummus', '1 wholemeal pitta', 'Tomato and lettuce'], steps: ['Chicken in the pan with salt and spices, 5 min per side.', 'Warm the pitta 1 min.', 'Assemble with the hummus and the veg.'] },
    'tortilla-patata': { name: 'Quick microwave potato omelette', ingredients: ['300 g potato', '3 eggs', 'Onion (optional)', 'Salt and olive oil'], steps: ['Diced potato with a little oil, covered in the microwave for 8 min.', 'Mix with the beaten eggs and salt.', 'Microwave 3-4 min more, or set it in the pan.'] },
    'yogur-almendras': { name: 'Protein yoghurt with almonds', ingredients: ['1 protein yoghurt (200 g)', '20 g almonds'], steps: ['Nothing to cook.'] },
    'tostada-cacahuete': { name: 'Toast with peanut butter and banana', ingredients: ['2 slices of wholemeal bread', '20 g peanut butter', '1 banana'], steps: ['Toast, spread, slice the banana on top.'] },
    'batido-proteina': { name: 'Protein shake with milk', ingredients: ['1 scoop of protein powder (30 g)', '300 ml milk'], steps: ['Shake.'], tip: 'The fastest and cheapest way to add 30 g of protein when the day is running tight.' },
    'requeson-fruta': { name: 'Cottage cheese with fruit and honey', ingredients: ['200 g cottage cheese or 0 % quark', '1 piece of fruit', '1 tsp honey'], steps: ['Mix.'] },
    'atun-tostadas': { name: 'Tuna on toast', ingredients: ['2 tins of tuna in brine', '2 slices of wholemeal bread', 'Tomato and oil'], steps: ['Toast the bread, rub tomato on it and add the drained tuna.'] },
  },
};
